

**** Value labels for IPUMS, Philippines, 2000

**** Copied from : https://international.ipums.org/international-action/variables/PH00A422/codes

** Paul Lambert/Dave Griffiths, Univ. Stirling, 27 October 2010


************************************************


#delimit ; 

capture label drop occlab; 

label define occlab
11	"Officers"
12	"Enlisted personnel"
111	"Government administrators (including career executive service off.)"
112	"Legislative officials"
113	"Traditional chiefs and heads of villages"
114	"Senior officials of special-interest organization"
121	"Directors and chief executives of corporations"
122	"Production and operations managers"
123	"Specialized managers"
131	"General managers/managing-proprietors"
141	"School supervisors and principals"
142	"Transport and communications service supervisors"
143	"Production supervisors and general foremen"
144	"Sales supervisors in wholesale and retail trade"
149	"Other supervisors not elsewhere classified"
211	"Physicists, chemists and related professionals"
212	"Mathematicians, statisticians and related professionals"
213	"Computer professionals"
214	"Architects and related professionals"
215	"Engineers and related professionals"
221	"Life science professionals"
222	"Health professionals (except nursing)"
223	"Nursing and midwifery professionals"
231	"College, university and higher education teaching professionals"
232	"Technical, vocational and related instructors"
233	"Secondary education teaching professionals"
234	"Elementary education teaching professionals"
235	"Special education teaching professionals"
239	"Teaching professionals not elsewhere classified"
241	"Business professionals"
242	"Legal professionals"
243	"Librarians, archivists and curators"
244	"Social and related science professionals"
245	"Writers and creative or performing artists"
246	"Religious Professionals"
311	"Physical science and engineering technicians"
312	"Computer assistants and computer equipment controllers"
313	"Optical and electronic equipment controllers"
314	"Ship and aircraft controllers and technicians"
315	"Building, safety, health and quality inspectors"
321	"Life science technicians and related associated professionals"
322	"Health associate professionals (except nursing)"
323	"Nursing and midwifery associate professionals"
324	"Traditional medicine practitioners"
330	"Teaching associate professionals"
341	"Finance and sales associate professionals"
342	"Business services agents and trade brokers"
343	"Administrative associate professionals"
344	"Customs, taxation, licensing, welfare and related professionals"
345	"Police inspectors and detectives"
346	"Social work associate professionals"
347	"Artistic, entertainment and sports associate professionals"
348	"Religious associate professionals"
411	"Secretaries and keyboard-operating clerks"
412	"Numerical clerks"
413	"Material recording and transport clerks"
414	"Library, mail and related clerks"
419	"Other Office Clerks"
421	"Cashiers, tellers and related clerks"
422	"Client information clerks"
511	"Travel attendants and related workers"
512	"Housekeeping and restaurant services workers"
513	"Personal care and related workers"
514	"Astrologers, fortune-tellers and related worker"
515	"Other personal services workers"
516	"Protective services workers"
521	"Fashion and other models"
522	"Shop salespersons and demonstrators"
523	"Stall and market salespersons"
611	"Field crop farmers"
612	"Orchard farmers"
613	"Ornamental and other plant growers"
621	"Livestock and dairy farmers"
622	"Poultry farmers"
629	"Other animal raisers"
631	"Forest tree planters"
632	"Concessionaires and loggers"
633	"Charcoal makers and related workers"
634	"Minor forest products gatherers"
641	"Aqua-farm cultivators"
642	"Inland and coastal waters fishermen"
643	"Deep-sea fishermen"
649	"Fishermen not elsewhere classified"
651	"Hunters and trappers"
659	"Hunters and trappers not elsewhere classified"
711	"Miners, shotfirers, stone cutters and carvers"
712	"Building frame construction and related trades"
713	"Building construction finishers and related trades workers"
714	"Painters and related trades workers"
721	"Metal molders, welders, and sheet-metal workers"
722	"Blacksmiths, tool-makers and related trades workers"
723	"Machinery mechanics, fitters and related trades workers"
724	"Electricians, electrical and electronic equipment workers"
731	"Precision workers in metal and related material"
732	"Potters, glass-makers and related trades workers"
733	"Handicraft workers in wood, textile, leather and related material"
734	"Printing, binding and related trades workers"
741	"Food processing and related trades workers"
742	"Wood treaters, cabinet-makers and related trades workers"
743	"Textile, garment and related trades workers"
744	"Leather and shoemaking trades workers"
811	"Mining-and mineral-processing plant operators"
812	"Metal processing plant operators"
813	"Glass, ceramics and related plant operators"
814	"Wood-processing and papermaking plant operators"
815	"Chemical-processing plant operators"
816	"Power-production and related plant operators"
817	"Automated assembly-line and industrial robot operators"
821	"Metal and mineral products machine operators"
822	"Chemical products machine operators"
823	"Rubber and plastic products machine operators"
824	"Wood products machine operators"
825	"Textile and leather products machine operators"
826	"Food and related products machine operators"
827	"Assemblers"
829	"Other machine operators and assemblers"
831	"Locomotive-engine drivers and related workers"
832	"Motor vehicle drivers"
833	"Agricultural and other mobile-plant operators"
834	"Ship's deck crews and related workers"
911	"Market stall vendors, street vendors and related workers"
912	"Shoe cleaning and other street services elementary workers"
913	"Domestic helpers and cleaners and related workers"
914	"Building caretakers, window and related cleaners"
915	"Messengers, porters, doorkeepers and related workers"
916	"Garbage collectors and related laborers"
921	"Agricultural, forestry and fishery laborers"
931	"Mining and construction laborers"
932	"Manufacturing laborers"
933	"Transport laborers and freight handlers"
950	"New workers seeking employment"
951	"Experienced workers seeking reemployment"
952	"Workers reporting occupations unidentifiable"
953	"Workers not reporting any occupation"
970	"No occupation"
998	"Unknown"
999	"NIU (not in universe)"  ;

#delimit cr 

**This do file was created as part of the Economic and Social Research Council funded project:
**Social Networks and Occupational Structure (ESRC grant no: RES-062-23-2497)
**Paul Lambert and Dave Griffiths, University of Stirling
*For more information on the project, see http://www.camsis.stir.ac.uk/sonocs/

 
