**** Value labels for IPUMS, Mexico, 1990

**** Copied from : https://international.ipums.org/international-action/variables/MX90A429/codes

** Paul Lambert/Dave Griffiths, Univ. Stirling, 22 October 2010


************************************************


#delimit ; 

capture label drop occlab; 

label define occlab
0	"NIU (not in universe)"
1100	"Architects"
1101	"Civil engineers and construction engineers"
1102	"Mining, metallurgy, and petroleum engineers"
1103	"Topography, hydrology, geology, and geodesic engineers"
1104	"Chemical, industrial, and mechanical engineers"
1105	"Electrical, electronic, information, and telecommunication engineers"
1109	"Other occupations that make up this subgroup"
1110	"Physicists and astronomers"
1111	"Mathematicians and statisticians"
1120	"Chemists"
1121	"Pharmacists"
1130	"General doctors and specialists"
1131	"Nursing professionals"
1132	"Dentists"
1133	"Ophthalmologists"
1134	"Professional in nutrition"
1135	"Biomedics and geneticists"
1139	"Other occupations that make up this subgroup"
1140	"Biologists"
1141	"Ecologists and professionals in atmospheric sciences"
1142	"Professionals in sea and oceanography sciences"
1150	"Agronomists"
1151	"Veterinarians and zoo technicians"
1152	"Forestation professionals"
1153	"Professionals in fishing and aquaculture"
1160	"Lawyers"
1161	"Sociologists and demographers"
1162	"Professionals in political sciences and public administration"
1163	"Anthropologists and historians"
1164	"Psychologists"
1165	"Professionals in philosophy and letters"
1166	"Educators"
1167	"Professionals in communication sciences"
1168	"Geographers"
1169	"Other occupations that make up this subgroup"
1170	"Economists"
1171	"Business administrators"
1172	"Professionals in archive and library sciences"
1173	"Public accountants"
1174	"Professionals in marketing"
1175	"Professionals in hotel management and tourism"
1180	"Religious professionals"
1190	"Other occupations that make up this group"
1200	"Technicians in architecture and industrial and graphic design"
1201	"Technicians in civil and construction engineering"
1202	"Technicians in mining, metallurgy, and petroleum engineering"
1203	"Technicians in topographic, hydraulic, geological and geodesic engineering"
1204	"Technicians in industrial, chemical, and mechanical engineering"
1205	"Technicians in electrical, electronic, information, and telecommunications engineering"
1206	"Technicians in operating film, projection, television and other recording equipment"
1209	"Other occupations that make up this subgroup"
1210	"Technicians in physics"
1211	"Technicians in mathematics and statistics"
1220	"Nurses and technicians in human medicine"
1221	"Technicians in dentistry and dental mechanics"
1222	"Optometrists and other technicians in optometry"
1223	"Nutritionists, dentists, and other technicians in nutrition and diet"
1229	"Other occupations that make up this subgroup"
1230	"Chemical and biological laboratory technicians"
1231	"Pharmaceutical laboratory technicians"
1239	"Other occupations that make up this subgroup"
1240	"Agronomy technicians"
1241	"Veterinary and zoology technicians"
1242	"Fishing technicians"
1243	"Forestry and forestation technicians"
1249	"Other occupations that make up this subgroup"
1250	"Technicians in social sciences"
1251	"Technicians in economic administrative sciences"
1260	"Personnel at the technical level in religious activities"
1290	"Other occupations that make up this group"
1300	"Professors in universities and other higher education establishments"
1310	"Vocational, preparatory and equivalent professors"
1320	"High school professors"
1330	"Elementary school professors"
1331	"Literacy teachers and bilingual teachers and promoters"
1340	"Preschool professors"
1350	"Teachers of people with mental deficiencies and behavioral problems"
1351	"Teachers of the blind"
1352	"Teachers of people with hearing and language deficiencies"
1353	"Teachers of persons with motor difficulties"
1359	"Other occupations that make up this subgroup"
1360	"Professor of physical education"
1361	"Professors of artistic education"
1362	"Professors of technical and commercial education"
1369	"Other occupations that make up this subgroup"
1390	"Other occupations that make up this group"
1400	"Writers and critics"
1401	"Newspaper reporters and writers"
1410	"Composers"
1411	"Singers"
1412	"Musicians"
1413	"Actors"
1414	"Dancers"
1419	"Other occupations that make up this subgroup"
1420	"Artistic painters and drawing artists"
1421	"Sculptors and engravers"
1422	"Photographers"
1423	"Choreographers and scene directors"
1424	"Decorators and designers"
1425	"Publicists"
1429	"Other occupations that make up this subgroup"
1430	"Directors of artistic productions"
1431	"Producers and organizers of artistic and cultural activities"
1432	"Announcers, directors, and commentators on radio and television"
1439	"Other occupations that make up this group"
1440	"Professional sportsmen and bullfighters"
1450	"Umpires and sports judges"
1451	"Sports trainers, instructors, and coordinators"
1490	"Other occupations that make up this group"
2100	"High-level government authorities and legislators"
2101	"Municipal presidents"
2110	"Presidents, directors, and general managers in decentralized public institutions and firms"
2111	"Presidents, directors, and general managers in private institutions and firms"
2119	"Other occupations that make up this subgroup"
2120	"Directors, managers, and administrators in health services"
2121	"Directors, managers, and administrators in administration and finances"
2122	"Directors, managers, and administrators in commercial activities"
2123	"Directors, managers, and administrators in communications and transportation"
2124	"Directors, managers, and administrators in industrial manufacturing activities"
2125	"Directors, managers, and administrators in social, cultural, personal and service services"
2126	"Directors and coordinators in the area of teaching and investment centers"
2127	"Managers and administrators of small businesses (movies, hotels, restaurants, sports, etc.)"
2128	"Directors, managers, and administrators in the agricultural sector"
2129	"Other occupations that make up this subgroup"
2130	"Directors of political parties"
2131	"Directors of business organizations"
2132	"Directors of union organizations"
2133	"Directors of humanitarian and religious organizations and civic associations"
2139	"Other occupations that make up this subgroup"
2190	"Other occupations that make up this group"
4100	"Workers in harvesting corn and/or beans"
4101	"Workers in harvesting cereals"
4102	"Workers in harvesting cotton and/or henequen"
4103	"Workers in harvesting vegetables"
4104	"Workers in harvesting coffee and/or cocoa"
4105	"Workers in harvesting tobacco"
4106	"Workers in harvesting fruit"
4107	"Workers in harvesting flowers"
4108	"Workers in other agricultural harvests not mentioned above"
4109	"Other occupations that make up this subgroup"
4110	"Workers in breeding bovine cattle"
4111	"Workers in breeding pigs"
4112	"Workers aviculture breeding"
4113	"Workers in breeding goats and sheep"
4114	"Beekeeping workers"
4115	"Workers in breeding small species (rabbits, pigeon, duck, etc.)"
4116	"Workers in breeding equines (horses, donkeys, mules)"
4119	"Other occupations that make up this subgroup"
4120	"Workers who combine agricultural activities with cattle"
4121	"Workers who carry out support services for agricultural production"
4130	"Lumbermen, log splitters, tree cutters, and similar"
4131	"Rubber, gum, and resin harvesters and similar"
4132	"Greenhouse or nursery (plant) workers"
4133	"Workers in activities that involve planting, reforesting, and conservation of forests"
4134	"Firewood cutters and collectors"
4135	"Producers of charcoal"
4136	"Workers in the collection of plants, herbs, and roots that are not cultivated"
4139	"Other occupations that make up this subgroup"
4140	"Workers in activities that involve hunting, trapping and similar occupations"
4150	"Fishermen"
4151	"Workers in aquaculture"
4159	"Other occupations that make up this subgroup"
4160	"Workers in activities involving processing agricultural products"
4161	"Workers in activities involving processing fishing products"
4169	"Other occupations that make up this subgroup"
4170	"Foremen, overseers and similar in agricultural activities"
4171	"Foremen, overseers and similar in cattle activities"
4172	"Foremen, overseers and similar in forestry activities"
4173	"Foremen, overseers and similar in fishing activities"
4179	"Other occupations that make up this subgroup"
4180	"Contractors of labor for agricultural, cattle, etc. activities"
4190	"Other occupations that make up this group"
5100	"Heads, coordinators, supervisors, and contractors in the production of foods, beverages, and tobacco"
5101	"Superintendents, inspectors, and examiners in the production of foods, beverages, and tobacco products"
5102	"Foremen, contractors, and production chiefs in the production of foods, beverages, and tobacco products"
5110	"Heads, coordinators, supervisors, and contractors in the extraction of mines, quarries, and wells"
5111	"Superintendents, inspectors, and examiners in the extraction of mines, quarries, and wells"
5112	"Foremen, contractors, and production chiefs in the extraction of mines, quarries, and wells"
5120	"Heads, coordinators, supervisors, and contractors in the production of textiles and leather and fur products"
5121	"Superintendents, inspectors, and examiners in the production of textiles, leather, furs, and similar"
5122	"Foremen, contractors, and production chiefs in the production of textiles, leather, furs, and similar"
5130	"Heads, coordinators, supervisors, and contractors in the production of wood and paper and printing"
5131	"Superintendents, inspectors, and examiners in the production of wood and paper, and printing"
5132	"Foremen, contractors, and production chiefs in the production of wood and paper and printing"
5140	"Heads, coordinators, supervisors, and contractors in the production of metal and restoring and maintenance"
5141	"Superintendents, inspectors, and examiners in the production of metal and in metal products, restoring and maintenance"
5142	"Foremen, contractors, and production chiefs in the production of metal products and manufacturing, restoring and maintenance"
5150	"Heads, coordinators, supervisors, and contractors in the production of wax, and glass and others"
5151	"Superintendents, inspectors, and examiners in the production of ceramic, glass, and others"
5152	"Foremen, contractors, and production chiefs in the production of ceramics, glass and other minerals"
5160	"Heads, coordinators, supervisors, and contractors in construction"
5161	"Superintendents, inspectors, and examiners in construction"
5162	"Foremen, contractors, and production chiefs in construction"
5170	"Heads, coordinators, supervisors, and contractors in the energy production, electricity and telecommunications"
5171	"Superintendents, inspectors, and examiners in the energy generation, electricity, and telecommunications"
5172	"Foremen, contractors, and production chiefs in the generation of energy, electricity, and telecommunications"
5180	"Heads, coordinators, supervisors, and contractors in the production of chemicals and petrochemicals"
5181	"Superintendents, inspectors, and examiners in the production of chemicals and petrochemicals"
5182	"Foremen, contractors, and production chiefs in the production of chemicals, petroleum, rubber, and plastics"
5190	"Other heads, coordinators, supervisors, and contractors not listed elsewhere"
5191	"Other superintendents, inspectors, and examiners not listed elsewhere"
5192	"Other foremen, contractors, and production chiefs not classified elsewhere"
5200	"Workers in the elaboration of meat and fish products and derivatives"
5201	"Workers in the elaboration of milk and dairy products"
5202	"Workers in the elaboration of bread, tortillas, and other cereal products"
5203	"Workers in the elaboration of products made with fruits and vegetables"
5204	"Workers in the elaboration of sugar, coffee, chocolate, tea, and candies"
5205	"Workers in the elaboration of tobacco products"
5206	"Workers in the elaboration of alcoholic and non-alcoholic beverages"
5207	"Workers in the elaboration of oils, greases, and spices"
5208	"Workers in the elaboration of foods"
5209	"Other occupations that make up this subgroup"
5210	"Miners"
5211	"Quarry workers (in the extraction of quarries, clay, sand, coal, etc.)"
5212	"Chipper, breaker, and masher in mine extraction"
5213	"Mine sampler"
5219	"Other occupations that make up this subgroup"
5220	"Fiber preparers"
5221	"Bobbin winders"
5222	"Weavers"
5223	"Tailors, clothing designers and seamstresses who produce clothing and hats"
5224	"Manufacture and pattern cutters in fabric, leather, fur, and similar"
5225	"Hand sewers and embroiderers"
5226	"Upholsterers"
5227	"Leather workers, cutters, tanners, and painters of leather and furs"
5228	"Shoemakers and similar workers"
5229	"Other occupations that make up this subgroup"
5230	"Carpenters, cabinetmakers, varnishers, wood finishers, and similar"
5231	"Artisans and factory workers in the manufacture of wood products and similar"
5232	"Artisans and factory workers in the manufacture of paper and cardboard products"
5233	"Printing and factory workers in binding and photogravure"
5234	"Linotypes, typesetters, and engravers"
5235	"Photograph developers and printers and similar"
5239	"Other occupations that make up this subgroup"
5240	"Mold makers and boiler makers"
5241	"Welders and oxyfuel cutters"
5242	"Metal coaters, chromists, and metal painters"
5243	"Jewelers, goldsmiths, silversmiths, tinsmiths, and bronze workers"
5244	"Locksmiths, metal polishers, and tool sharpeners"
5245	"Mechanics, adjusters, and workers in the maintenance and repair of motor vehicles"
5246	"Mechanics, adjusters, and workers in the maintenance and repair of machinery, etc."
5247	"Mechanics, adjusters, and workers in the maintenance and repair of musical instruments"
5248	"Blacksmiths, decorative metal workers, and forge workers"
5249	"Other occupations that make up this subgroup"
5250	"Clay workers and ceramic workers"
5251	"Workers in the manufacture of marble, porcelain, tiles and similar"
5252	"Workers in the manufacture of cement, limestone, chalk, concrete and similar products"
5253	"Glass workers and similar"
5254	"Workers in the manufacture of products made of bone, shell, coral, and similar"
5259	"Other occupations that make up this subgroup"
5260	"Construction day laborers"
5261	"Wide-brush painters"
5262	"Chalk workers, crown makers, and other workers who cover ceiling and walls"
5263	"Roofer (installers of shingles, etc.)"
5264	"Mosaic installers, tile installers, and installers of floors and pavements"
5265	"Installers of insulators and climate controls"
5266	"Installers of materials for impermeablizing, glass, wall paper, carpets, and other materials"
5267	"Plumbers, pipe fitters, and pipe installers"
5269	"Other occupations that make up this subgroup"
5270	"Electricians and linemen"
5271	"Repairmen of electro-domestic appliances"
5272	"Repairmen of radios, televisions, and electronic equipment"
5273	"Installers and repairmen of telegraphs and telephones"
5274	"Installers and repairmen of telecommunication equipment"
5275	"Repairmen of electromechanical appliances"
5279	"Other occupations that make up this subgroup"
5280	"Workers in the manufacture and repair of rubber products"
5281	"Workers in the manufacture of chemical substances and compounds"
5290	"Other occupations that make up this subgroup"
5300	"Operators of machinery for the preparation of meat, fish and derivatives"
5301	"Operators of machinery for the production of milk and dairy products"
5302	"Operators of machinery for the production of bread, tortillas, pastries and other products"
5303	"Operators of machinery for the preparation of fruits and vegetables"
5304	"Operators of machinery for the production of sugar, coffee, chocolate, tea, and candies"
5305	"Operators of machinery for the production of tobacco and cigarettes"
5306	"Operators of machinery for the production of alcoholic and non-alcoholic beverages"
5307	"Operators of machinery for the production of oils, fats, and spices"
5309	"Other occupations that make up this subgroup"
5310	"Operators of machinery and equipment used for extraction in mines and quarries"
5311	"Operators of machinery and equipment used for extraction in petroleum wells"
5312	"Operators of machinery and equipment used for obtaining water"
5319	"Other occupations that make up this subgroup"
5320	"Operators of machines for threading and bobbin winding"
5321	"Operators of looms and machinery for manufacturing knits, textiles, etc."
5322	"Operators of sewing machines, embroidering machines, and machines for cutting fabric in textile production"
5323	"Operators in machinery in the production of footwear and manufacture of products made of leather and furs"
5324	"Operators of machinery for whitening, dying, etc., textile products, leather and furs"
5329	"Other occupations that make up this subgroup"
5330	"Operators of machinery for treating triply and layered wood and fabrics"
5331	"Operators of machinery in the manufacture of cellulose and paper manufacture"
5332	"Operators of machinery for manufacture of wood products and similar"
5333	"Operators of machinery for printing and binding"
5334	"Operators of machinery for the manufacture of paper and cardboard products"
5335	"Operators of machinery of developing and printing photographic work and similar"
5339	"Other occupations that make up this subgroup"
5340	"Operators of metallurgy ovens, filters, and laminators"
5341	"Operators of machinery for the thermal treatment of metals"
5342	"Operators of machinery for flattening and stretching metals"
5343	"Operators of machinery for die pressing and shredding metals"
5344	"Operators of tooling machines for metals (lathes, drills, etc.)"
5345	"Operators of machinery for polishing, galvanizing, and coating metals"
5346	"Operators of machinery in the manufacture of machinery, and metal products and parts"
5347	"Assembly and installation of precision machinery and instruments"
5348	"Assembly and installation of electric and electronic parts"
5349	"Other occupations that make up this subgroup"
5350	"Operators of machinery in the production of ceramic goods"
5351	"Operators of machinery in the production of marble, mosaic, tiles, and similar"
5352	"Operators of machinery in the production of cement, limestone, chalk, and similar"
5353	"Operators of machinery in the production of glass products"
5354	"Operators of machinery in the production of non-metal minerals"
5359	"Other occupations that make up this subgroup"
5360	"Operators of specialized portable equipment for construction"
5370	"Operators of installation and plants that generate and distribute electrical energy"
5371	"Operators of turbines, boilers, and steam machines"
5372	"Operators of equipment for telecommunications and electronic control"
5373	"Operators of equipment for pumping, ventilation, and refrigeration"
5379	"Other occupations that make up this subgroup"
5380	"Operators of machinery and equipment for breaking, crushing and mixing chemical products"
5381	"Operators of machinery and equipment for treating water and chemical substances"
5382	"Operators of machinery and equipment in petroleum refineries and natural gas industries"
5383	"Operators of machinery for manufacturing pharmaceutical products and cosmetics"
5384	"Operators of machinery for manufacturing photographic products"
5385	"Operators of machinery for manufacturing and retreading tires"
5386	"Operators of machinery for manufacturing and assembling plastic products, etc."
5389	"Other occupations that make up this subgroup"
5390	"Other occupations that make up this group"
5400	"Assistants, helpers, and workers in the production of food, beverages, and tobacco products"
5401	"Suppliers, feeders, recovery and classification in the production of food, beverages, and tobacco"
5402	"Carriers, loaders and unloaders in the production of food, beverages, and tobacco products"
5403	"Packers, packagers, and bottlers in the production of food, beverages, and tobacco products"
5410	"Assistants, helpers, and workers in the extraction from mines, quarries, and wells"
5411	"Carriers, loaders and unloaders in extraction from mines, quarries, and wells"
5420	"Assistants, helpers, and workers in textile production, leather production and similar"
5421	"Suppliers, feeders, recovery and classification in the production of textile and leather"
5422	"Carriers, loaders and unloaders in textile, leather, fur and similar production"
5423	"Packers, packagers, and bottlers in the production of textiles, leather, fur and similar"
5430	"Assistants, helpers, and workers in the production of wood, paper, and printing"
5431	"Suppliers, feeders, recovery and classification in the production of wood, paper, and printing"
5432	"Carriers in the production of wood, paper, and printing products"
5433	"Packers and packagers in the production of wood, paper, and printing products"
5440	"Assistants and similar in the production of metal and manufacture of machinery"
5441	"Suppliers and similar in the production of metal and manufacture of machinery"
5442	"Carriers, loaders and unloaders in the production of metal and manufacture of machinery"
5443	"Packers, packagers, and bottlers in metal production and manufacture of machinery"
5450	"Assistants, helpers, and workers in the production of ceramic, glass and non-metal materials"
5451	"Suppliers, feeders, and recovery in the production of ceramics, glass and non-metal materials"
5452	"Carriers, loaders and unloaders in the production of ceramics and other non-metal minerals"
5453	"Packers, packagers, and bottlers in metal production and manufacture of ceramics and other non-metal minerals"
5460	"Assistants, helpers, and workers in the construction"
5461	"Carriers, loaders and unloaders in the construction"
5470	"Assistants, helpers, and workers in production of energy, electricity and telecommunications"
5471	"Carriers, loaders and unloaders in the production of energy, electricity and telecommunications"
5472	"Packers, packagers, and bottlers in the production of energy, electricity and telecommunications"
5480	"Assistants, helpers, and workers in chemical and petrochemical industries and production"
5481	"Suppliers, feeders, recovery and classification in the production of chemicals and petrochemicals"
5482	"Carriers, loaders and unloaders in chemical and petrochemical production"
5483	"Packers, packagers, and bottlers in chemical and petrochemical production"
5490	"Other assistants, helpers, and workers not classified elsewhere"
5491	"Other suppliers, feeders, recovery and classification not listed elsewhere"
5492	"Other carriers, loaders and unloaders not classified elsewhere"
5493	"Other packers, packagers, and bottlers not classified elsewhere"
5500	"Conductors of mobile agricultural machinery"
5501	"Conductors of mobile construction machinery"
5502	"Conductors of mobile machinery for moving merchandise in factories, ports, etc."
5509	"Other occupations that make up this subgroup"
5510	"Conductors of railroad transportation (train, metro, light rail)"
5511	"Assistants to the conductors in railroad transportation"
5520	"Conductors of buses, trolleys, and passenger buses"
5521	"Drivers of cargo trucks"
5522	"Taxi drivers and drivers of cars and small buses"
5523	"Assistants to the drivers"
5529	"Other occupations that make up this subgroup"
5530	"Drivers of air transportation"
5540	"Drivers of maritime transportation"
5541	"Machinist officers"
5542	"Deck officers"
5543	"Motor boat drivers, boaters, and operators of small boats"
5549	"Other occupations that make up this subgroup"
5550	"Drivers of transportation vehicles that use human force"
5551	"Drivers of transportation vehicles that use animal force (carts, mule trains)"
5590	"Other occupations that make up this group"
6100	"Heads of department, section and area"
6101	"Administrative coordinators and supervisors"
6102	"Assistants to the head [of department, etc]"
6103	"Regulation inspectors"
6104	"Contractor, coordinator and traffic supervisor for air, maritime, railroad and land traffic"
6109	"Other occupations that make up this subgroup"
6110	"Secretaries"
6111	"Typists, short-hand takers, stenographers"
6112	"Copyists"
6120	"Workers at mid- and lowers level in accounting"
6121	"Workers at mid- and lowers level in banking and finances"
6122	"Workers at mid- and lowers level in elaboration of statistics"
6123	"Accounts payable, cashiers, account collectors"
6124	"Ticket vendors and ticket office workers"
6129	"Other occupations that make up this subgroup"
6130	"Operators of office machinery (copier, mimeograph, telex, etc.)"
6131	"Operators of electronic processing equipment"
6139	"Other occupations that make up this subgroup"
6140	"Workers in a library, newspaper library, library of tape recordings, and museums"
6141	"Workers in an archive and correspondence"
6142	"Control workers in stores and warehouses"
6149	"Other occupations that make up this subgroup"
6150	"Receptionists and other workers who attend the public"
6151	"Workers in travel agencies"
6152	"Workers in administrative services in general"
6159	"Other occupations that make up this subgroup"
6160	"Telephone operators"
6161	"Telegraph operators"
6169	"Other occupations that make up this subgroup"
6170	"Mailmen"
6171	"Workers in messenger services in general"
6179	"Other occupations that make up this subgroup"
6180	"Dispatch, inspection and similar occupations in air transportation"
6181	"Dispatch, inspection and similar occupations in maritime transportation"
6182	"Dispatch, inspection and similar occupations in railroad transportation"
6183	"Dispatch, inspection and similar occupations in land transportation"
6189	"Other occupations that make up this subgroup"
6190	"Other occupations that make up this group"
7100	"Commerce in general and specialized commerce in fixed establishments"
7110	"Agents and supervisors of commerce"
7111	"Employees and dependents of commerce"
7120	"Exhibitors"
7121	"Dispatchers"
7122	"Delivery persons"
7130	"Sales agents, representatives, distributors, and suppliers"
7131	"Real estate agents, and agents in services of real-estate rental"
7132	"Agents of stocks, bonds, and other investment titles"
7133	"Insurance agents"
7134	"Assessors"
7135	"Auctioneers"
7139	"Other occupations that make up this subgroup"
7190	"Other occupations that make up this group"
7200	"Newspaper vendors who walk the streets to sell"
7201	"Lottery vendors who walk the streets to sell"
7202	"Vendors who walk the streets to sell diverse articles"
7209	"Other occupations that make up this subgroup"
7210	"Vendors and preparers of foods on the roadside"
7211	"Shoeshiners"
7212	"Car washers and car watchers"
7213	"Clowns, contortionists, and similar occupations carried out on the roadside"
7219	"Other occupations that make up this subgroup"
7290	"Other occupations that make up this group"
8100	"Restaurateurs (they prepare and serve food)"
8101	"Bartenders, waiters, and room keepers"
8102	"Hotel workers, bellhops, and workers in the hospitality services"
8103	"Employees in clothing care (dressing rooms)"
8104	"Stewardesses and flight attendants"
8109	"Other occupations that make up this subgroup"
8110	"Laundresses"
8111	"Dyers"
8112	"Pressers"
8119	"Other occupations that make up this subgroup"
8120	"Porters and concierges"
8121	"Lift and elevator operators"
8122	"Luggage carriers and store packagers"
8123	"Cleaning workers in offices, schools, hospitals and other establishments"
8124	"Gardeners"
8125	"Merchandise loaders and unloaders"
8129	"Other occupations that make up this subgroup"
8130	"Hairdressers, barbers, and stylists"
8131	"Hairstylists, make up artists, manicurists, and pedicurists"
8132	"Bathers and massage therapists"
8140	"Workers in real estate rental services"
8150	"Animators and announcers"
8151	"Magicians, illusionists, imitators, and similar workers in an establishment"
8152	"Clowns, contortionists, circus workers and similar occupations in an establishment"
8160	"Support workers for carrying out entertainment, tourism and sports activities"
8161	"Workers in the care and assistance to persons (do not include nurses)"
8162	"Prostitution workers"
8169	"Other occupations that make up this subgroup"
8170	"Workers in funeral services and cemeteries"
8190	"Other occupations that make up this subgroup"
8200	"Administrators in domestic services"
8201	"Workers in domestic services in general and specialized domestic services"
8202	"Persons dedicated to caring for the elderly, persons who are ill, and children in private homes"
8209	"Other occupations that make up this group"
8300	"Firemen (fire fighters)"
8301	"Police and transit agents"
8302	"Detectives"
8303	"Watchmen and guards"
8304	"Personnel of customs and migration"
8309	"Other occupations that make up this subgroup"
8310	"Workers of the air force"
8311	"Workers of the navy"
8312	"Workers of the army (land-based armed forces)"
8319	"Other occupations that make up this subgroup"
8390	"Other occupations that make up this group"
9900	"Other occupations not classified above"
9910	"Not sufficiently specified"
9920	"Not specified"
9996	"Other occupations that make up this subgroup"
9999	"Unknown"  ;

#delimit cr 


**This do file was created as part of the Economic and Social Research Council funded project:
**Social Networks and Occupational Structure (ESRC grant no: RES-062-23-2497)
**Paul Lambert and Dave Griffiths, University of Stirling
*For more information on the project, see http://www.camsis.stir.ac.uk/sonocs/

 
