
** 'CO80' labels for UK 1980 Occupations.
** (From the 'CO80' file available at http://www.camsis.stir.ac.uk/Data/Britain91.html ).

** THIS CODING FRAME IS FOR THE F5.2 FORMAT TITLE MULTIPLED BY 100, E.G. C080 1.02 AND 160.01 ARE CODED AS 102 AND 16001 . 


** Coding frame taken from  http://home.fsw.vu.nl/hbg.ganzeboom/ISMF/ismf.htm (ENG84W_occ.sps).
** Citation for this resource: 
*    Ganzeboom, H. B. G., & Treiman, D. J. (2007). International Stratification and Mobility File [ISMF], Occupational 
*     Labels and Recodes. Amsterdam / Los Angeles: Free University / UCLA-ISSR, retrieved 1 June 2007.


**   Stata re-formatting macro: Paul Lambert, Univ. Stirling, 24/12/2009.




#delimit; 

capture label drop co80l;
 
label define co80l  
   100  "judges barristers advocates solicitors "          
   200  "accountants valuers finance specialists "          
   201  "chartered & certified accountants "          
   202  "cost & works accountants   "          
   203  "estimators "          
   204  "valuers claims assessors   "          
   205  "financial mngr "          
   206  "underwriters brokers investment analysts    "          
   207  "taxation experts   "          
   300  "personnel & industrial relations mngr "          
   301  "personnel & industrial relations officers   "          
   302  "o & m work study & or officers  "          
   400  "economists statisticians systems analysts computer "          
   401  "economists statisticians actuaries    "          
   402  "systems analysts computer programmers "          
   500  "marketing mngrg    "          
   501  "marketing & sales mngr & executives   "          
   502  "advertising & pr executives "          
   503  "buyers (retail trade)  "          
   504  "buyers & purchasing officers (not retail)   "          
   600  "statutory & other inspectors    "          
   601  "environmental health officers   "          
   602  "building inspectors    "          
   603  "inspectors (statutory & similar) "          
   700  "gen admintr-national gvnmnt "          
   701  "gen admintr-national gvnmnt "          
   702  "gen admintr-national gvnmnt "          
   800  "local gvnmnt officers (admin & exec)  "          
   900  "all other profssnl & related support mngmnt "          
   901  "company secretaries    "          
   902  "officials of trade associations trade unions "          
   903  "property & estate mngr "          
   904  "librarians information officers "          
   905  "legal service & related occs    "          
   906  "management consultants "          
   907  "mngr' personal assistants  "          
   908  "profssnl wkr & related support mngmnt nec   "          
   1000  "teachers in higher educ    "          
   1001  "univ academic staff    "          
   1002  "teachers in establishments for further & higher educ    "          
   1100  "teachers nec   "          
   1200  "vocational & industrial trainers educ officers s  "          
   1201  "vocational & industrial trainers "          
   1202  "educ officers school inspectors "          
   1203  "social & behavioral scientists  "          
   1300  "welfare wkr    "          
   1301  "matrons houseparents   "          
   1302  "paygroup leaders   "          
   1303  "welfare occs nec   "          
   1400  "clergy ministers of religion    "          
   1500  "medical & dental practitioners  "          
   1501  "medical practitioners  "          
   1502  "dental practitioners   "          
   1600  "nurse admintr nurses   "          
   1700  "pharmacists radiographers therapists nec    "          
   1701  "pharmacists    "          
   1702  "medical radiographers  "          
   1703  "ophthalmic & dispensing opticians "          
   1704  "physiotherapists   "          
   1705  "chiropodists   "          
   1706  "therapists nec "          
   1800  "all other profssnl & related in educ welfare "          
   1801  "medical technicians dental auxiliaries "          
   1802  "veterinarians  "          
   1803  "driving instructors (not hgv)   "          
   1804  "profssnl & related in educ-welfare-health nec "          
   1900  "authors writers journalists "          
   2000  "artists designers windown dressers    "          
   2001  "artists commercial artists "          
   2002  "industrial designers (not clothing)   "          
   2003  "clothing designers "          
   2004  "window dressers    "          
   2100  "actors musicians entertainers stage mngr    "          
   2101  "actors entertainers singers stage mngr "          
   2102  "musicians  "          
   2200  "photographers cameramen sound & vision equipment  "          
   2201  "photographers cameramen    "          
   2202  "sound & vision equipment operators    "          
   2300  "all other literary artistic & sports  "          
   2301  "professional sportsmen sports officials "          
   2302  "literary artistic & sports wkr nec    "          
   2400  "scientist physic mathematicians "          
   2401  "biological scientist biochemists "          
   2402  "chemical scientists    "          
   2403  "physical & geological scientists math "          
   2500  "civil municipal mining & quarrying engine   "          
   2600  "mech & aero engineers  "          
   2601  "mech & aero engineers  "          
   2602  "design & development engineers (mechanical) "          
   2700  "electrical & electronic engineers "          
   2701  "electrical engineers   "          
   2702  "electronic engineers   "          
   2800  "engineers & technologists nec   "          
   2801  "chemical engineers "          
   2802  "production engineers   "          
   2803  "planning & quality control engineers  "          
   2804  "engineers nec  "          
   2805  "metallurgists  "          
   2806  "technologists nec  "          
   2900  "draughtsmen    "          
   3000  "lab & engnrng technicians engineer    "          
   3001  "lab technicians    "          
   3002  "engineering technicians technician engineers "          
   3100  "architects town planners quantity building & l&   "          
   3101  "architects town planners   "          
   3102  "quantity surveyors "          
   3103  "building l& & mining surveyors  "          
   3200  "officers (ships & aircraft) air traffic planners & "          
   3201  "aircraft flight deck officers   "          
   3202  "air traffic planners & controllers    "          
   3203  "deck engnring & radio officers & pilots ship "          
   3300  "profssnl & related in science engnring & othe "          
   3301  "architect & town planning technicians "          
   3302  "building & civil engnring technicians "          
   3303  "technical & related wkr nec "          
   3400  "production works & maintenance mngrs foremen "          
   3500  "site & other mngr agents & clerks of works gene   "          
   3501  "mngr in building & contracting  "          
   3502  "manager clerks of works    "          
   3600  "mngr in transport warehousing public utilities &  "          
   3601  "mngr in mining & public utilities "          
   3602  "transport mngr "          
   3603  "stores controllers "          
   3604  "mngr in warehousing & materials h&ling nec  "          
   3700  "office mngr    "          
   3701  "credit controllers "          
   3702  "office mngr nec    "          
   3800  "mngr in wholesale & retail distribution "          
   3801  "garage proprietors "          
   3802  "butchers (mngr & proprietors)   "          
   3803  "fishmongers (mngr & proprietors) "          
   3804  "other proprietors & mngr (sales) "          
   3900  "mngr of hotels clubs etc. & in entertainment &    "          
   3901  "hotel & residential club mngr   "          
   3902  "publicans  "          
   3903  "restaurateurs  "          
   3904  "club stewards  "          
   3905  "entertainment & sports mngr "          
   4000  "farmers horticulturists farm mngr "          
   4100  "officers uk armed forces   "          
   4200  "officers foreign & commonwealth armed forces "          
   4300  "senior police prison & fire service officers "          
   4301  "prison officers (chief officers & above)    "          
   4302  "police officers (inspectors & above)  "          
   4303  "fire service officers  "          
   4400  "all other mngr "          
   4401  "proprietors & mngr service flats holiday flats    "          
   4402  "mngr of laundry & dry cleaning receiving shops    "          
   4403  "hairdressers' & barbers' mngr & proprietors "          
   4404  "mngr nec   "          
   4500  "supvis of clerks civil service exec officers "          
   4501  "civil service executive officers "          
   4502  "supvis of stores & despatch clerks    "          
   4503  "supvis of tracers drawing office assistants "          
   4504  "supvis of other clerks & cashiers (not retail)    "          
   4505  "supvis of retail shop cashiers check-out & cash   "          
   4600  "clerks     "          
   4601  "stores & despatch clerks   "          
   4602  "tracers & drawning office assistants  "          
   4603  "other clerks   "          
   4700  "retail shop cashiers check-out & cash & wrap operato    "          
   4800  "supvis of typists office & machine operators "          
   4801  "supvis of typists shorth& writers secretaries "          
   4802  "supvis of  office machine operators   "          
   4803  "supvis of  telephone operators  "          
   4804  "superviosr of  radio & telegraph operators  "          
   4900  "secretaries shorth& typists receptionists   "          
   4901  "receptionist   "          
   4902  "typists shorth& writers secretaries   "          
   5000  "office machine operators   "          
   5100  "telephonists radio & telegraph operators    "          
   5101  "telephonist receptionists  "          
   5102  "telephone operators    "          
   5103  "radio & telegraph operators "          
   5200  "supvis of postmen mail sorters messengers   "          
   5201  "supvis of postmen mail sorters  "          
   5202  "supvis of messengers   "          
   5300  "postmen mail sorters messengers "          
   5301  "postmen mail sorters   "          
   5302  "messengers "          
   5400  "sales supvis   "          
   5401  "supvis of shop salesmen & assistants  "          
   5402  "supvis of petrol pump forecourt attendants  "          
   5403  "supvis of roundsmen van salesmen "          
   5500  "salesmen sales assistants shop assistants shelf filler  "          
   5501  "shop salesmen & assistants "          
   5502  "shelf fillers  "          
   5503  "petrol pump forecourt attendants "          
   5600  "roundsmen van salesmen "          
   5700  "sales representatives & agents  "          
   5701  "importers exporters commodity brokers "          
   5702  "market & street traders & assistants  "          
   5703  "scrap dealers general dealers rag & bone merchants "          
   5704  "credit agents collector salesmen "          
   5705  "sales representatives  "          
   5706  "sales repr (property & services) other agents "          
   5800  "ncos & other ranks uk armed forces    "          
   5900  "ncos & other ranks foreign & commonwealth armed forc    "          
   6000  "supvis (police sergeants fire fighting & related) "          
   6001  "police sergeants   "          
   6002  "fire service supviss   "          
   6003  "prison service principal officers "          
   6004  "supvis of security guards & officers patrolmen    "          
   6005  "supvis of traffic wardens  "          
   6006  "supvis of security & protective service wkrs nec  "          
   6100  "policemen firemen prison officers "          
   6101  "policemen (below sergeant) "          
   6102  "firemen    "          
   6103  "prison officers (below principal officer)   "          
   6200  "other security & protective service wkr "          
   6201  "security guards & officers patrolmen watchmen "          
   6202  "traffice wardens   "          
   6203  "security & protective service wkr nec "          
   6300  "catering supvis    "          
   6301  "supvis of chefs cooks  "          
   6302  "supvis of waiters waitresses    "          
   6303  "supvis of barmen barmaids  "          
   6304  "supvis of counter h&s assistants "          
   6400  "chefs cooks    "          
   6500  "waiters & barstaff "          
   6501  "waiters    "          
   6502  "barstaff   "          
   6600  "counter h&s assistants kitchen porters h&s  "          
   6601  "counter h&s assistants "          
   6602  "kitchen porters h&s    "          
   6700  "supvis-housekeeping & related   "          
   6701  "housekeepers (non-domestic) "          
   6702  "supvis of other domestic & school helpers   "          
   6703  "supvis of travel stewards & attendants "          
   6704  "supvis of hospital porters "          
   6705  "supvis of hotel porters    "          
   6706  "supvis of ambulancemen "          
   6707  "supvis of hospital ward orderlies "          
   6800  "domestic staff & school helpers "          
   6801  "domestic housekeepers  "          
   6802  "nursery nurses "          
   6803  "other domestic & school helpers "          
   6900  "travel stewards & attendants hospital & hotel porter    "          
   6901  "travel stewards & attendants    "          
   6902  "hospital porters   "          
   6903  "hotel porters  "          
   7000  "ambulancemen hospital orderlies "          
   7001  "ambulancemen   "          
   7002  "hospital ward orderlies    "          
   7100  "supvis foremen-caretaking cleaning & related "          
   7101  "supvis of caretakers   "          
   7102  "supvis of clearners window-chimney cleaners "          
   7103  "supvis of railway stationment   "          
   7104  "supvis of lift & car park attendants  "          
   7200  "caretakers road sweepers & other cleaners   "          
   7201  "caretakers "          
   7202  "cleaners window cleaners chimney-road sweepers    "          
   7300  "hairdressing supvis    "          
   7400  "hairdressers barbers   "          
   7500  "all other in catering cleaning & other personal servic  "          
   7501  "railway stationmen "          
   7502  "lift & car park attendants "          
   7503  "launderers dry cleaners pressers "          
   7504  "undertakers    "          
   7505  "bookmakers betting shop mngr    "          
   7506  "service wkr nec    "          
   7600  "foremen-farming horticulture forestry "          
   7601  "farm foremen   "          
   7602  "horticultural foremen  "          
   7603  "foremen gardeners & groundsmen  "          
   7604  "agric machinery foremen    "          
   7605  "forestry foremen   "          
   7606  "other foremen in farming & related    "          
   7700  "farm wkr   "          
   7800  "horticultural wkr gardners groundsmen "          
   7801  "horticultural wkr  "          
   7802  "gardeners groundsmen   "          
   7900  "agric machinery drivers operators "          
   8000  "forestry wkr   "          
   8100  "supvis mates-fishing   "          
   8200  "fishermen  "          
   8300  "all other in farming & related  "          
   8400  "foremen tannery & leather (including leather substitute "          
   8401  "foremen tannery production wkrs "          
   8402  "foremen shoe repairers "          
   8403  "foremen leather cutters & sewers footwear lasters maker "          
   8404  "foremen other making & repairing leather    "          
   8500  "tannery & leather (including leather substitutes) wkr   "          
   8501  "tannery production wkr "          
   8502  "shoe repairers "          
   8503  "leather cutters & sewers footwear lasters   "          
   8600  "foremen-textile processing "          
   8601  "foremen preparatory fibre processors  "          
   8602  "foremen spinners doublers twisters    "          
   8603  "foremen winders reelers    "          
   8604  "foremen warp preparers "          
   8605  "foremen weavers    "          
   8606  "foremen knitters   "          
   8607  "foremen bleachers dyers finishers "          
   8608  "foremen menders darners    "          
   8609  "foremen other material processing textiles  "          
   8700  "textile wkr    "          
   8701  "preparatory fibre processors    "          
   8702  "spinners doublers twisters "          
   8703  "winders reelers    "          
   8704  "warp preparers "          
   8705  "weavers    "          
   8706  "knitters   "          
   8707  "bleachers dyers finishers  "          
   8708  "menders darners    "          
   8800  "foremen-chemical processing "          
   8900  "chemical gas & petroleum process plant operators  "          
   9000  "foremen-food & drink processing "          
   9001  "foremen bakers flour confectioners    "          
   9002  "foremen butchers meat cutters   "          
   9003  "foremen fishmongers poultry dressers  "          
   9004  "foremen brewery & vinery process wkr  "          
   9005  "foremen bakery & confectionery wkr    "          
   9006  "foremen food & drink nec   "          
   9100  "bakers flour confectioners "          
   9200  "butchers   "          
   9201  "butchers meat cutters  "          
   9202  "fishmongers poultry dressers    "          
   9300  "foremen-paper & board making & paper products "          
   9301  "foremen paper paperboard & leatherboard wkr "          
   9302  "foremen bookbinders & finishers "          
   9303  "foremen cutting & slitting machine operators "          
   9304  "foremen other material processing wood & paper    "          
   9305  "foremen other making & repairing paper goods & printing "          
   9400  "paper board & paper product makers bookbinders    "          
   9401  "paper paperboard & leatherboard wkr   "          
   9402  "bookbinders & finishers    "          
   9403  "cutting & slitting machine operators paper & paper "          
   9500  "foremen-glass ceramincs rubber plastics etc. "          
   9501  "foremen glass & ceramics furnacemen kilnsetters   "          
   9502  "foremen glass formers & shapers finishers decorators    "          
   9503  "foremen casters & other pottery makers "          
   9504  "foremen rubber process wkr moulding machine operator    "          
   9505  "foremen cal&er & extruding machine operators moulders   "          
   9506  "foremen man-made fibre makers   "          
   9507  "foremen washers screeners & crushers in mines & quarries"          
   9508  "foremen glass & ceramics making "          
   9509  "foremen rubber making  "          
   9510  "foremen plastics making    "          
   9600  "glass & ceramics furnacemen & wkr "          
   9601  "glass & ceramics furnacemen kilnsetters "          
   9602  "glass formers & shapers finishers decorators "          
   9603  "casters & other pottery makers  "          
   9700  "rubber & plastics wkr  "          
   9701  "rubber worker  "          
   9702  "calendar & extruding machine operators "          
   9800  "all other in processing materials (other than metal)    "          
   9801  "man-made fibre makers  "          
   9802  "brewery & vinery process wkr    "          
   9803  "washers screeners & crushers in mines & quarries  "          
   9804  "textiles   "          
   9805  "bakery & confectionery wkr "          
   9806  "tobacco    "          
   9807  "food & drink nec   "          
   9808  "wood & paper   "          
   9809  "all other (excluding metal) nec "          
   9900  "foremen-printing   "          
   9901  "foremen compositors    "          
   9902  "foremen electrotypers stereotypers printing plate "          
   9903  "foremen printing machine minders & assistants "          
   9904  "foremen screen & block printers "          
   9905  "foremen printers (so described) "          
   10000  "printing wkr screen & block printers  "          
   10001  "compositors    "          
   10002  "electrotypers stereotypers printing plate & cylinder    "          
   10003  "printing machine minders & assistants "          
   10004  "screen & block printers    "          
   10005  "printers (so described)    "          
   10100  "foremen-textile materials working "          
   10101  "foremen tailors tailoresses dressmakers "          
   10102  "foremen clothing cutters milliners furriers "          
   10103  "foremen sewers embroiderers "          
   10104  "foremen coach trimmers upholsterers mattress makers "          
   10105  "foremen carpet fitters "          
   10106  "foremen other making & repairing clothing & related "          
   10200  "tailors dressmakers an other clothing wkr   "          
   10201  "tailors tailoresses dressmakers "          
   10202  "clothing cutters milliners furriers   "          
   10203  "sewers embroiderers    "          
   10300  "coach trimmers upholsterers mattress makers "          
   10400  "foremen-woodworking    "          
   10401  "foremen carpenters joiners "          
   10402  "foremen cabinet makers "          
   10403  "foremen case & box makers  "          
   10404  "foremen pattern makers (moulds) "          
   10405  "foremen sawyers veneer cutters woodworking machinists   "          
   10406  "foremen other making & repairing wood "          
   10500  "woodwkr pattern makers "          
   10501  "carpenters joiners "          
   10502  "cabinet makers "          
   10503  "case & box makers  "          
   10504  "pattern makers (moulds)    "          
   10600  "sawyers veneer cutters woodworking machinists "          
   10700  "all other in making & repairing (excluding metal & "          
   10701  "labourers & mates to woodworking craftsmen  "          
   10702  "dental technicians "          
   10703  "carpet fitters "          
   10704  "muscial instrument makers piano tuners "          
   10705  "glass & ceramics maker "          
   10706  "wood maker repairer    "          
   10707  "leather maker  "          
   10708  "clothing & related products maker repairer  "          
   10709  "paper goods & printing "          
   10710  "rubber     "          
   10711  "plastics   "          
   10712  "all other (excluding metal & electrical) nec "          
   10800  "foremen-metal making & treating "          
   10801  "foremen furnace operating occs (metal) "          
   10802  "foremen rollermen  "          
   10803  "foremen smiths forgemen    "          
   10804  "foremen metal drawers  "          
   10805  "foremen moulders coremakers die casters "          
   10806  "foremen electroplaters "          
   10807  "foremen annealers hardeners temperers (metal) "          
   10808  "foremen galvanizers tin platers dip platers "          
   10809  "foremen metal making & treating wkr nec "          
   10900  "furnacemen (metal) rollerman smiths forgemen "          
   10901  "furnace operators  "          
   10902  "rollermen  "          
   10903  "forgemen   "          
   11000  "metal drawers moulders die casters eletroplaters  "          
   11001  "metal drawers  "          
   11002  "moulders coremakers die casters "          
   11003  "electroplaters "          
   11004  "annealers hardners temperers (metal)  "          
   11100  "foremen-engineering machining   "          
   11101  "foremen press & machine tool setters  "          
   11102  "foremen centre lathe turners    "          
   11103  "foremen machine tool setter operators "          
   11104  "foremen machine tool operators  "          
   11105  "foremen press stamping & automatic machine operators    "          
   11106  "foremen metal polishers    "          
   11107  "foremen fettlers dressers  "          
   11108  "foremen shot blasters  "          
   11200  "press & machine tool setter operators & operators "          
   11201  "press & machine tool setters    "          
   11202  "centre lathe turners   "          
   11203  "machine tool setter operators   "          
   11204  "machine tool operators "          
   11300  "machine attendants minders press & stamping machine "          
   11301  "press stamping & automatic machine operators "          
   11302  "metal polishers    "          
   11303  "fettlers dressers  "          
   11400  "formen-production fitting (metal) "          
   11401  "foremen tool makers tool fitters markers-out "          
   11402  "foremen precision instrument makers & repairers   "          
   11403  "foremen watch & chronometer makers & repairers    "          
   11404  "foremen metal working production fitters & fitter "          
   11405  "foremen motor mechanics auto engineers "          
   11406  "foremen maintenance fitters (aircraft engines)    "          
   11407  "foremen office machinery mechanics    "          
   11500  "tool makers tool fitters markers-out  "          
   11600  "instrument & watch & clock makers & repairers "          
   11601  "precision instrument makers & repairers "          
   11602  "watch & chronometer makers & repairers "          
   11700  "metal working production fitters & fitter-machinists    "          
   11800  "motor vehicle & aircraft mechanics    "          
   11801  "motor mechanics auto engineers  "          
   11802  "maintenance fitters (aircraft engines) "          
   11900  "office machinery mechanics "          
   12000  "foremen-production fitting & wiring (electrical)  "          
   12001  "foremen production fitters (electircal electronic) "          
   12002  "foremen electricians electrical maintenance fitters "          
   12003  "foremen plant operators & attendants nec    "          
   12004  "foremen telephone fitters  "          
   12005  "foremen cable jointers linesmen "          
   12006  "foremen radio & tv mechanics    "          
   12007  "foremen other electronic maintnenace engineers    "          
   12100  "production fitters elect power plant  "          
   12101  "production fitters (electrical eletronic)   "          
   12102  "electricians electrical maintenance fitters "          
   12103  "electrical engineers (so described)   "          
   12104  "plant operators & attendants nec "          
   12200  "telephone fitters cable jointers linesmen   "          
   12201  "telephone fitters  "          
   12202  "cable jointers linesmen    "          
   12300  "ratio tv & other electronic maintenance fitters & "          
   12301  "ratio & tv mechanics   "          
   12302  "other electronic maintenance engineers "          
   12400  "foremen-metal working pipes sheets structures "          
   12401  "foremen plumbers heating & ventilating fitters gas fitt "          
   12402  "foremen sheet metal wkr    "          
   12403  "foremen metal plate wkr shopwrights riveters "          
   12404  "foremen steel erectors benders fixers "          
   12405  "foremen scaffolders stagers "          
   12406  "foremen welders    "          
   12407  "foremen riggers    "          
   12500  "plumbers heating & ventilating fitters gas fitters "          
   12600  "sheet metal wkr platers shipwrights riveters etc. "          
   12601  "sheet metal wkr    "          
   12602  "metal plate wkr shipwrights riveters  "          
   12700  "steel erectors scaffolders steel benders fixers   "          
   12701  "steel erectors benders fixers   "          
   12702  "sacffolders stagers    "          
   12800  "welders    "          
   12801  "welders    "          
   12900  "foremen-other processing making & repairing (metal an   "          
   12901  "foremen goldsmiths silversmiths precious stone wkr "          
   12902  "foremen engravers etchers (printing)  "          
   12903  "foremen coach & vehicle body builders "          
   12904  "foremen oilers greasers lubricators   "          
   12905  "foremen electronics wiremen "          
   12906  "foremen coil winders   "          
   13000  "goldsmiths silversmiths etc engravers etchers "          
   13001  "goldsmiths silversmiths precious stone wkr  "          
   13002  "engravers etchers (printing)    "          
   13100  "all other in processing making & repairing (metal & "          
   13101  "coach & vehicle body builders   "          
   13102  "galvanizers tin platers dip platers   "          
   13103  "metal making & treating wkr nec "          
   13104  "oilers greasers lubricators "          
   13105  "riggers    "          
   13106  "electronics wiremen    "          
   13107  "coil winders   "          
   13108  "shot blasters  "          
   13109  "other metal jewellery electrical production wkr   "          
   13110  "forment (engnring & allied trades)    "          
   13111  "trainee craftsmen (engnring & allied trades) "          
   13200  "foremen-painting & similar coating    "          
   13201  "foremen pottery decorators "          
   13202  "foremen coach painters (so described) "          
   13203  "foremen other spray painters    "          
   13204  "foremen painters & decorators nec french polishers "          
   13300  "painters decorators french polishers  "          
   13301  "pottery decorators "          
   13302  "coach painters (so described)   "          
   13303  "other spray painters   "          
   13304  "painters & decorators nec french polishers  "          
   13400  "foremen-product assembling (repetitive) "          
   13401  "foremen assemblers-electrical electronic    "          
   13402  "foremen assemblers-instruments  "          
   13403  "foremen assemblers-vehicles & other metal goods   "          
   13404  "foremen assemblers-paper production processing    "          
   13405  "foremen assemblers-plastics goods "          
   13500  "repetitive assemblers (metal & electrical goods)  "          
   13501  "assemblers (electrical electronic)    "          
   13502  "instrument assemblers  "          
   13503  "assemblers (vehicles & other metal goods)   "          
   13600  "foremen-product inspection & packaging "          
   13601  "foremen inspector-metal electrical goods    "          
   13602  "foremen inspector-textiles "          
   13603  "foremen inspector-food "          
   13604  "foremen inspector-rubber goods  "          
   13605  "foremen inspector-plastics goods "          
   13606  "foremen inspector-woodwork "          
   13607  "foremen-packers bottlers canners fillers    "          
   13608  "foremen-laboratory assistants   "          
   13609  "foremen-inspectors sorters in paper productionin  "          
   13610  "foremen-weighters  "          
   13611  "foremen-graders sorters selectors in nec    "          
   13700  "inspectors viewers testers packers bottlers etc.  "          
   13701  "inspectors viewers (metal electrical goods) "          
   13702  "packers bottlers canners fillers "          
   13800  "all other in painting repetitive assembling product "          
   13801  "lab assistants "          
   13802  "inspector-textiles "          
   13803  "inspector-food "          
   13804  "inspector-rubber goods "          
   13805  "inspector-plastics goods   "          
   13806  "inspector-woodwork "          
   13807  "inspectors sorters in paper production processing "          
   13808  "assemblers in paper production processing & printing    "          
   13809  "assemblers (plastics goods) "          
   13810  "weighers   "          
   13811  "graders sorters selectors nec   "          
   13812  "painting assembling & related occ nec "          
   13900  "foremen-building & civil engineering nec    "          
   13901  "foremen bricklayers tile setters "          
   13902  "foremen masons stone cutters    "          
   13903  "foremen plasterers "          
   13904  "foremen roofers glaziers   "          
   13905  "foremen h&ymen general building wkr   "          
   13906  "foremen railway lengthmen  "          
   13907  "foremen road surfacers concreters "          
   13908  "foremen roadmen    "          
   13909  "foremen paviors kerb layers "          
   13910  "foremen sewage plant attendants "          
   13911  "foremen mains & service layers pipe jointers "          
   13912  "foremen construction wkr nec    "          
   14000  "building & construction wkr "          
   14001  "bricklayers tile setters   "          
   14002  "masons stone cutters   "          
   14003  "plasterers "          
   14004  "roofers glaziers   "          
   14005  "h&ymen general building wkr "          
   14006  "paviors kerb layers    "          
   14100  "concreters road surfacers railway lengthmen "          
   14101  "railway lengthmen  "          
   14102  "road surfacers concreters  "          
   14103  "roadmen    "          
   14104  "paviors kerb layers    "          
   14200  "sewage plant attendants sewermen "          
   14201  "sewage plant attendants    "          
   14202  "mains & service layers pipe jointers  "          
   14300  "civil engnring laborers craftsmen's mates   "          
   14301  "craftsmen's mates  "          
   14302  "building & civil engnring labourers   "          
   14400  "foremen-deputies-coalmining "          
   14500  "face-trained coalmining wkr "          
   14600  "all other in construction mining quarrying drilling "          
   14601  "miners (not coal) quarrymen well drillers   "          
   14602  "construction wkr nec   "          
   14700  "foremen-ships lighters & other vessels "          
   14800  "deck engine-room h&s bargemen lightermen boatmen  "          
   14900  "foremen-rail transport operating "          
   14901  "foremen railway guards "          
   14902  "foremen signalmen & crossing keepers railway "          
   14903  "foremen shunters pointsmen "          
   14904  "foremen other foremen rail transport  "          
   15000  "rail transport operating staff  "          
   15001  "drivers motormen secondmen railway engines  "          
   15002  "railway guards "          
   15003  "signalmen & crossing keepers railway  "          
   15004  "shunters pointsmen "          
   15100  "foremen-road transport operating but inspectors   "          
   15101  "bus inspectors "          
   15102  "foremen drivers of road goods vehicles "          
   15103  "other foremen road transport    "          
   15200  "bus coach & lorry drivers  "          
   15201  "bus & coach drivers    "          
   15202  "drivers of road goods vehicles  "          
   15203  "other motor drivers    "          
   15300  "bus conductors drivers' mates   "          
   15301  "bus conductors "          
   15302  "drivers' mates "          
   15400  "foremen-civil engnring plant operating materials  "          
   15401  "foremen mechanical plant drivers operators  "          
   15402  "foremen crane drivers operators "          
   15403  "foremen fork lift mechanical truck drivers  "          
   15404  "foremen slingers   "          
   15500  "mechanical plant fork lift mechanical truck drivers "          
   15501  "mechanical plant drivers operators (earth moving  "          
   15502  "crane drivers operators    "          
   15503  "fork lift mechanical truck drivers    "          
   15600  "foremen-materials moving & storing    "          
   15601  "foremen storekeepers warehousemen "          
   15602  "foremen stevedores dockers "          
   15603  "foremen goods porters  "          
   15604  "foremen refuse collectors dustmen "          
   15700  "storekeepers stevedores warehouse market & other  "          
   15701  "storekeepers warehousemen  "          
   15702  "stevedores dockers "          
   15703  "goods porters  "          
   15704  "refuse collectors dustment "          
   15800  "all other in transport operating materials moving & "          
   15801  "slingers   "          
   15802  "wkr in transport operating materials moving "          
   15900  "foremen-miscellaneous  "          
   15901  "foremen laborer-textiles (not textile goods) "          
   15902  "foremen laborer-chemicals & allied trades   "          
   15903  "foremen laborer-coke ovens & gas works "          
   15904  "foremen laborer-glass & ceramics "          
   15905  "foremen laborer-foundries in engnring & allied trades   "          
   15906  "foremen laborer-engineering & allied trades "          
   15907  "foremen laborer-coal mines "          
   15908  "foremen laborer-other  "          
   15909  "foremen laborer-boiler operators "          
   16000  "gen laborers   "          
   16001  "laborer-textiles (not textile goods)  "          
   16002  "laborer-chemicals & allied trades "          
   16003  "laborer-coke ovens & gas works  "          
   16004  "laborer-glass & ceramics   "          
   16005  "laborer-foundries in engnring & allied trades "          
   16006  "laborer-engineering & allied trades   "          
   16007  "laborer-coal mines "          
   16008  "laborer-other  "          
   16100  "all other in misc occ nec  "          
   16101  "boiler operators   "          
   16102  "all other in misc occ nec  "     ;



#delimit cr

     
