
** 'KOS60' labels for UK 1960 Occupations.


** Coding frame taken from  http://home.fsw.vu.nl/hbg.ganzeboom/ISMF/ismf.htm (ENG63_occ.sps).
** Citation for this resource: 
*    Ganzeboom, H. B. G., & Treiman, D. J. (2007). International Stratification and Mobility File [ISMF], Occupational 
*     Labels and Recodes. Amsterdam / Los Angeles: Free University / UCLA-ISSR, retrieved 1 June 2007.


**   Stata re-formatting macro: Paul Lambert, Univ. Stirling, 24/12/2009.




#delimit; 

capture label drop kos60l;
 
label define kos60l  
    0 "fisherman"
    1 "farmers, farm managers, market gardeners"
    2 "agric wrkr, nec  "
    3 "agric machinery drivers   "
    4 "gardeners-groundsmen  "
    5 "foresters-woodmen"
    6 "fishermen-crofters scotland only   "
    7 "crofters scotland only"
    10 "coal mine-face wrkr   "
    11 "coal mine-other undergr wrkr   "
    12 "coal mine-wrkr above gr so described"
    13 "unknown miner?   "
    14 "wrkr below ground nec "
    15 "surface wrkr nec-mines-quarries"
    20 "furnacemen, coal, gas,-coke ovens  "
    21 "chemical production process wrkr nec"
    30 "ceramic formers  "
    31 "glass formers finishers-decorators "
    32 "furnacemen, kilnmen, glass-ceramic "
    33 "ceramics decorators-finishers  "
    34 "glass-ceramics prod proc wrkr nec  "
    40 "furnacemen - metal"
    41 "rolling, tube mill oprts, metal drawers "
    42 "moulders-coremakers foundry"
    43 "smith, forgemen  "
    44 "metal making-treating wrkr nec "
    45 "fettlers, metal dressers  "
    50 "radio-radar mechanics "
    51 "installers-repairmen, telephone"
    52 "linesmen, cable jointers  "
    53 "electricians "
    54 "electrical-electronic fitters  "
    55 "assemblers electrical-electronic   "
    56 "electrical engs so described   "
    60 "sheet metal wrkr "
    61 "constructional engs - riggers  "
    62 "metal plate wrkr - riveters"
    63 "gas, electric welders, cutters, braziers"
    64 "machine tool setters, setter-oprts "
    65 "machine tool oprts"
    66 "tool makers, tool room fitters "
    67 "fitters, machine erectors, etc "
    68 "engs so described"
    69 "electroplaters, dip platers-related wrkr"
    70 "plumbers, lead burners, pipe fitters"
    71 "press wrkr-stampers   "
    72 "metal wrkr, nec  "
    73 "watch-chronometer makers-repairers "
    74 "precision instrument makers-repairers   "
    75 "goldsmiths, silversmiths, jewellery makers  "
    76 "coach, carriage, wagon builders-repairers   "
    77 "inspectors metal-electrical goods  "
    78 "other metal making, working, jewellery  "
    79 "elec prod proc wrkr   "
    80 "carpenters-joiners"
    81 "cabinet makers   "
    82 "sawyers-wood working machinists"
    83 "coopers, hoop makers-benders   "
    84 "pattern makers   "
    85 "woodwrkr nec "
    90 "tanners, leather, fur dressers, fellmongers "
    91 "shoemakers-shoe repairers "
    92 "cutters, lasters, sewers, footwear arw  "
    93 "leather products makers nec"
    100 "fibre preparers  "
    101 "spinners, doublers, winders, reelers"
    102 "warpers, sizers, drawers-in"
    103 "weavers "
    104 "knitters"
    105 "bleachers-finishers of textiles"
    106 "dyers of textiles"
    107 "textile fabrics-related products makers -examiners nec"
    108 "textile fabrics, etc, production process wrkr, nec   "
    109 "winders-reelers, rope, twine-net makers "
    110 "tailors, dress, light clothing makers   "
    111 "upholsterers-related wrkr "
    112 "sewers-embroiderers, texile-light leather prod   "
    113 "clothing-related products makers nec"
    120 "bakers-pastry cooks   "
    121 "butchers-meat cutters "
    122 "brewers, wine makers-related wrkr  "
    123 "food processors nec   "
    124 "tobacco preparers-products makers  "
    130 "makers of paper-paperboard"
    131 "paper products makers "
    132 "compositors  "
    133 "printing press oprts  "
    134 "printers so described "
    135 "printing wrkr nec"
    140 "wrkr in rubber   "
    141 "worker in plastic"
    142 "craftsmen nec"
    143 "other production process wrkr  "
    150 "bricklayers, tile setters "
    151 "mason, stone cutters, slate wrkr   "
    152 "plasterers, cement finishers, terazzo wrkr  "
    153 "builders so described, clerks of works  "
    154 "construction wrkr nec "
    160 "aerographers, paint sprayers   "
    161 "painters, decorators nec  "
    170 "boiler firemen   "
    171 "crane-hoist oprts, slingers"
    172 "oprts of earth moving-other constr machinery  nec"
    173 "boiler scalers   "
    174 "stationary engine, oprts nec oiler "
    180 "railway lengthmen"
    181 "chemical-allied trades"
    182 "enging-allied trades  "
    183 "foundries in enging-allied trades  "
    184 "textiles not textile goods"
    185 "coke ovens-gas works  "
    186 "glass-ceramics   "
    187 "building-contracting  "
    188 "other   "
    190 "deck, enging officers-pilots, ship "
    191 "deck-engineroom ratings, barge-boatmen  "
    192 "aircraft pilots, navigators-flight engs "
    193 "drivers, motormen, firemen, railway engine  "
    194 "railway guards   "
    195 "drivers of buses, coaches, trams   "
    196 "drivers of other road passenger vehicles"
    197 "drivers of road goods vehicles "
    198 "inspectors, supervisors transport  "
    199 "shunters, pointsmen   "
    200 "traffic controllers-dispatchers, transport  "
    201 "telephone oprts  "
    202 "telegraph-radio oprts "
    203 "postmen, mail sorters "
    204 "messengers   "
    205 "bus-tram conductors   "
    206 "porters, ticket collectors, railway"
    207 "stevedores, dock labourers"
    208 "lorry drivers mates, van guards"
    209 "wrkr in transport-commun occupations nec"
    210 "warehousemen, storekeepers-assistants   "
    211 "packers, labellers-related wrkr"
    220 "typists, shorthand writers, secretaries "
    221 "clerks, cashiers, office machine oprts  "
    222 "civil service executive officers   "
    223 "civil servants, local authority officials so descri           bed  "
    230 "proprietors-managers, food sales   "
    231 "proprietors-managers, non-food sales"
    232 "shop salesmen-assistants, food "
    233 "shop salesmen-assistants, non-food "
    234 "roundsmen bread, milk, laundry, soft drinks "
    235 "street vendors, hawkers   "
    236 "garage proprietors"
    237 "commercial travellers, manufacturers agents "
    238 "finance, insurance brokers, financial agents"
    239 "salesmen, services, valuers, auctioneers"
    250 "fire brigade officers-men "
    251 "police officers-men   "
    252 "guards-related wrkr nec   "
    253 "publicans, innkeepers "
    254 "barmen, barmaids "
    255 "lodging house, hotel keepers, housekeepers, stewards-matrons  "
    256 "restaurateurs, waiters, counter hands   "
    257 "cooks   "
    258 "kitchen hands"
    259 "maids, valets-related service wrkr nec  "
    260 "caretakers, office keepers"
    261 "chimney sweeps   "
    262 "charwomen, office cleaners, window cleaners "
    263 "hairdressers, manucurists, beauticians  "
    264 "launderers, dry cleaners-pressers  "
    265 "athletes, sportsmen-related wrkr   "
    266 "hospital or ward orderlies, ambulance men   "
    267 "service, sport-recreation wrkr nec "
    270 "ministers of the crown, mps nec senior government l  "
    271 "local authority senior officers"
    272 "managers in enging-allied trades   "
    273 "managers in building-contracting   "
    274 "managers in mining-production nec  "
    275 "personnel managers"
    276 "sales managers   "
    277 "company directors"
    278 "managers nec "
    280 "medical practitioners qualified"
    281 "dental practitioners  "
    282 "nurses  "
    283 "pharmacists, dispensers   "
    284 "radiographers medical-industrial   "
    285 "medical wrkr nec "
    286 "university teachers   "
    287 "teachers nec "
    288 "civil, structural, municipal engs  "
    289 "mechanical engs  "
    290 "electrical engs  "
    291 "technologists  nec"
    292 "chemists, physical-biological sciences  "
    293 "authors, journalists-related wrkr  "
    294 "stage managers, actors, entertainers, musicians  "
    295 "painters, sculptors-related creative artists"
    296 "accountants, professional, company secretaries registrars "
    297 "surveyors, architects "
    298 "clergy, ministers, members of religious orders   "
    299 "judges, barristers, advocates, solicitors   "
    310 "social welfare-related wrkr"
    311 "professional wrkr nec "
    312 "draughtsmen  "
    313 "laboratory assistants, technicians "
    314 "technical-related wrkr nec"
    320 "armed forces uk  "
    321 "armed forces commonwealth-foreign  ."
    330 "inadequately described occupations "
    400 "no occupation, housewife  "
    500 "information refused   "
    600 "student "
    999 "no respondent  "  ; 






#delimit cr
