**** Value labels for IPUMS, Vietnam, 1999

**** Copied from : https://international.ipums.org/international-action/variables/VN99A429/codes

** Paul Lambert/Dave Griffiths, Univ. Stirling, 29 October 2010


************************************************


#delimit ; 

capture label drop occlab; 

label define occlab

0	"Armed forces"
111	"Vietnamese communism party at central"
112	"Vietnamese communism party at the provincial level"
113	"Vietnamese communism party at the district level"
114	"Vietnamese communism party at the commune level"
115	"Enterprise and other organization"
131	"Government"
132	"Ministries, branches and equivalent institution belonging to the Government"
141	"Supreme People court and Peoples court of investigation"
142	"Local People court and Peoples court of investigation"
151	"People's council"
152	"People's committee at local (including the professional institutions)"
161	"Union institution (excluding the trade-union)"
162	"Trade-union"
171	"Occupation-employer and humanity organizations"
172	"Humanity organizations for other special interest"
181	"Leader of united institution, general corporation (and equivalent), big high-education institution"
182	"Director, deputy director of production branch-unit belonging to the united"
183	"Director, deputy director of other unit belonging to the united"
191	"Director, deputy director of company, enterprise manufacturing"
211	"Physicists, chemists and related professionals"
213	"Computing professionals"
214	"Architects, engineers and related professionals"
221	"Life science professionals"
222	"Health professionals (except nursing)"
223	"Nursing and midwifery professionals"
231	"College, university and higher education teaching professionals"
232	"Secondary vocational, lower and upper secondary education teaching professionals"
233	"Primary and Pre-primary education teaching professionals"
234	"Special education teaching professionals (teach physically or me"
235	"Other teaching professionals"
241	"Business professionals"
242	"Legal professionals"
243	"Archivists, librarians and related information professionals"
244	"Social science and related professionals"
245	"Writers and creative or performing artists"
246	"Religious professionals"
300	"Other physical and engineering science associate professionals"
311	"Physical and engineering science technicians"
312	"Computer associate professionals"
313	"Optical and electronic equipment operators"
314	"Ship and aircraft controllers and technicians"
315	"Safety and quality inspectors"
321	"Life science technicians and related associate professionals"
322	"Modern health associate professionals (except nursing)"
323	"Nursing and midwifery associate professionals"
324	"Traditional medicine practitioners and faith healers"
331	"Primary education teaching associate professionals"
332	"Pre-primary education teaching associate professionals"
333	"Special education teaching associate professionals"
334	"Other teaching associate professionals"
341	"Finance and sales associate professionals"
342	"Business services agents and trade brokers"
343	"Administrative associate professionals"
344	"Customs, tax and related government associate professionals"
345	"Police inspectors and detectives"
346	"Social work associate professionals"
347	"Artistic, entertainment and sports associate professionals"
348	"Religious associate professionals"
400	"Office clerks, n.s."
411	"Secretaries and keyboard-operating clerks"
412	"Numerical clerks"
413	"Material-recording and transport clerks"
414	"Library, mail and related clerks"
419	"Other office clerks"
421	"Cashiers, tellers and related clerks"
422	"Client information clerks"
500	"Personal and protective services workers, n.s."
511	"Travel attendants and related workers"
512	"Housekeeping and restaurant services workers"
513	"Personal care and related workers"
514	"Other personal services workers"
515	"Astrologers, fortune-tellers and related workers"
516	"Protective services workers"
520	"Other models, salespersons and demonstrators"
521	"Fashion and other models"
522	"Shop salespersons and demonstrators"
523	"Stall and market salespersons"
600	"Market-oriented skilled agricultural and fishery workers, n.s."
611	"Market gardeners and crop growers"
612	"Market-oriented animal producers and related workers"
613	"Market-oriented crop and animal producers"
614	"Forestry and related workers"
615	"Fishery workers, hunters and trappers"
711	"Miners, set-off-mine workers, stone cutters and carvers"
712	"Building frame and related trades workers"
713	"Building finishers and related trades workers"
714	"Painters, building structure cleaners and related trades workers"
721	"Metal molders, welders, sheet-metal workers, structural-metal p"
722	"Blacksmiths, tool-makers and related trades workers"
723	"Machinery mechanics and fitters"
724	"Electrical and electronic equipment mechanics and fitters"
731	"Precision workers in metal and related materials"
732	"Potters, glass-makers and related trades workers"
733	"Handicraft workers in wood, textile, leather and related material"
734	"Printing and related trades workers"
741	"Food processing and related trades workers"
742	"Wood treaters, cabinet-makers and related trades workers"
743	"Textile, garment and related trades workers"
744	"Pelt, leather and shoemaking trades workers"
790	"Craft and other related trades workers"
800	"Stationary-plant and related operators, n.s."
811	"Mining and mineral-processing-plant operators"
812	"Metal-processing-plant operators"
813	"Glass, ceramics and related plant operators"
814	"Wood-processing and papermaking-plant operators"
815	"Chemical-processing-plant operators"
816	"Power-production and related plant operators"
817	"Automated-assembly-line and industrial-robot operators"
821	"Metal and mineral-products machine operators"
822	"Chemical-products machine operators"
823	"Rubber- and plastic-products machine operators"
824	"Wood-products machine operators"
825	"Printing-, binding- and paper-products machine operators"
826	"Textile-, fur- and leather-products machine operators"
827	"Food and related products machine operators"
828	"Assemblers"
829	"Other machine operators and assemblers"
831	"Locomotive-engine drivers and related workers"
832	"Motor-vehicle drivers"
833	"Agricultural and other mobile-plant operators"
834	"Ship deck crews and related workers"
900	"Sales and services elementary occupations, n.s."
911	"Street vendors and related workers"
912	"Shoe cleaning and other street services elementary occupations"
913	"Domestic and related helpers, cleaners and launderers"
914	"Building caretakers, window and related cleaners"
915	"Messengers, porters, doorkeepers and related workers"
916	"Garbage collectors and related labourers"
920	"Other agricultural, fishery and related labourers"
921	"Agricultural, fishery and related labourers"
930	"Other labourers in mining, construction, manufacturing and transport"
931	"Mining and construction labourers"
932	"Manufacturing labourers"
933	"Transport labourers and freight handlers"
934	"Other elementary occupations"
997	"Response suppressed"
998	"Not reported"
999	"NIU (not in universe)"  ;

#delimit cr 


**This do file was created as part of the Economic and Social Research Council funded project:
**Social Networks and Occupational Structure (ESRC grant no: RES-062-23-2497)
**Paul Lambert and Dave Griffiths, University of Stirling
*For more information on the project, see http://www.camsis.stir.ac.uk/sonocs/


