**** Value labels for IPUMS, Venezuela, 2001

**** Copied from : https://international.ipums.org/international-action/variables/VE01A431/codes

** Paul Lambert/Dave Griffiths, Univ. Stirling, 29 October 2010


************************************************


#delimit ; 

capture label drop occlab; 

label define occlab

0	"NIU (not in universe)"
11	"Armed forces"
100	"Managers, directors, and bosses not well specified"
111	"Member s of the executive power and legislative bodies"
112	"Directive personnel of the public administration"
113	"Leaders of small populations"
114	"Managers and administrators of specialized organizations"
121	"General directors and general managers of businesses"
122	"Directors of production and operations departments"
123	"Other department directors"
131	"Managers of businesses"
200	"University students with degrees, and/or actors, painters, sculptors, and similar, not well specified"
211	"Physicists, chemists, and similar"
213	"Professionals of informatics"
214	"Architects, engineers, and similar"
221	"Professionals in biological sciences"
222	"Doctors and similar professionals (except nursing and midwife personnel)"
223	"Upper level nursing and midwife personnel"
230	"Professionals in education and teaching"
231	"Professors in universities and other institutions of higher education"
232	"Professors in secondary education"
233	"Upper level teachers in elementary and pre-school education"
235	"Other professionals in education"
241	"Specialists in organization and administration of businesses and similar"
242	"Professionals in law (legal professionals)"
243	"Archivists, librarians, document archivists, and similar"
244	"Specialists in social and human sciences"
245	"Writers, creative and performing artists"
246	"Catholic priests"
300	"Technicians and mid-level professionals, not well specified"
311	"Technicians in physical and chemical sciences and engineering"
312	"Technicians in informatics programming and control"
313	"Operators of optical and electronical equipment"
314	"Technicians in maritime and aeronautical navigation"
315	"Inspectors of construction jobs, security, health, and quality control"
321	"Mid-level technicians in biological sciences, agronomy, zoo technology, and similar"
322	"Mid-level technicians in modern medicine and healthcare (except nursing personnel)"
323	"Mid-level nursing and midwife personnel"
324	"Practitioners of traditional medicine and folk-healers"
331	"Mid-level teachers in elementary education"
332	"Mid-level teachers in pre-school education"
333	"Mid-level teachers in special education"
334	"Other mid-level teachers and instructors"
341	"Mid-level professionals in financial and commercial operations"
342	"Commercial agents and brokers"
343	"Mid-level professionals in administration services"
344	"Agents of public administrations in customs, taxes, and similar"
345	"Police inspectors and detectives"
346	"Mid-level social workers and assistants"
347	"Mid-level professionals in artistic activities, entertainment, and sports"
400	"All of the occupations related to administration, not clearly specified"
411	"Secretaries and operators of office equipment"
412	"Accounting and financial assistants"
413	"Employees in charge of registry of materials and transportation"
414	"Employees of libraries and mail services and similar"
421	"Cashiers, ticket vendors, and similar"
422	"Employees of services of information to clients"
500	"Wholesale and retail sales, businesses, and services, not well specified"
511	"Personnel in direct services to passengers"
512	"Personnel in intendancy and restaurant services (fast food)"
513	"Workers in personal care and similar"
514	"Other workers in personal services to individuals"
515	"Astrologists, fortunetellers, and similar"
516	"Personnel in services of protection and security"
521	"Models in fashion, art, and publicity"
522	"Salesmen and demonstrators in stores and shops"
523	"Vendors in kiosks and market stalls"
600	"Agriculture, animal breeding, fishing, not well specified"
611	"Farmers and specialized workers in market crops"
612	"Specialized breeders and workers in raising animals for the market and similar"
613	"Specialized agricultural producers and workers whose production is sent to market"
614	"Specialized forestry workers and similar"
615	"Fishermen, hunters, and trappers"
621	"Subsistence agricultural workers and fishermen"
700	"Artisan, small and mid-sized businesses, shops (mechanics, electricians, blacksmiths), plumbers and similar, not well specified"
711	"Miners, quarry workers, stone masons and workers"
712	"Officials and operators in construction (large works) and similar"
713	"Officials and operators in construction (finishing jobs) and similar"
714	"Painters, building-front cleaners, and similar"
721	"Mold-press workers, welders, laminators, boilermakers, assemblers of metal structures, and similar"
722	"Blacksmiths, toolmakers, and similar"
723	"Machine mechanics and adjusters"
724	"Mechanics and adjusters of electrical and electronic equipment"
731	"Precision mechanics in metals and similar materials"
732	"Potters, operators in glass factories, and similar"
733	"Artisans in wood, textiles, leather and similar materials"
734	"Officials and operators in graphic arts and similar"
741	"Officials and operators in food processing and similar"
742	"Officials and operators in wood treatment, cabinetmakers, and similar"
743	"Officials and operators in textiles, clothing production, and similar"
744	"Officials and operators in hides, leather, and footwear"
800	"All workers, operators, drivers of transportation and other specialized workers not well specified"
811	"Operators of mining installations, and mineral extraction and processing"
812	"Operators of metal processing installations"
813	"Operators of glass, ceramic, and similar installations"
815	"Operator of chemical treatment installations"
816	"Operators of installations for producing energy and similar"
821	"Operators of machines for working metals and mineral products"
823	"Operators of machines for manufacturing rubber products and plastic materials"
825	"Operators of printing and binding machinery and the manufacture of paper products"
826	"Operators of machinery for manufacturing textile products and articles made of hides and leather"
827	"Operators of machinery for preparation of foods and similar products"
829	"Other operators of machinery and assemblers"
831	"Locomotive machinists and similar"
832	"Drivers of motor vehicles"
833	"Operators of mobile agricultural machinery and other mobile machinery"
834	"Deck sailors and similar"
900	"All workers, operators, drivers of transportation and other specialized workers not well specified"
911	"Traveling salesmen and similar"
913	"Domestic personnel and similar, cleaners, clothes washers and pressers"
914	"Concierges, window washers and similar"
915	"Messengers, delivery persons, doormen, and similar"
916	"Trash collectors and similar"
921	"Day laborers in agriculture, forestry, fishing, and similar"
931	"Day laborers in mining and construction"
932	"Day laborers in the manufacturing industry"
933	"Day laborers in transportation"
999	"Not well specified"  ;

#delimit cr

**This do file was created as part of the Economic and Social Research Council funded project:
**Social Networks and Occupational Structure (ESRC grant no: RES-062-23-2497)
**Paul Lambert and Dave Griffiths, University of Stirling
*For more information on the project, see http://www.camsis.stir.ac.uk/sonocs/

 
