**** Value labels for IPUMS, Mexico, 2000

**** Copied from : https://international.ipums.org/international-action/variables/MX00A439/codes

** Paul Lambert/Dave Griffiths, Univ. Stirling, 22 October 2010


************************************************


#delimit ; 

capture label drop occlab; 

label define occlab
0	"NIU (not in universe)"
1100	"Architects and urbanists"
1101	"Civil and construction engineers"
1102	"Mining, metallurgic, and petroleum engineers"
1103	"Topographic, hydrologic, geologic, and geodesic engineers"
1104	"Chemical, industrial, and mechanical engineers"
1105	"Electrical, electronic, informatics, and telecommunications engineers"
1106	"Biomedical engineers"
1109	"Other professionals who perform an occupation related to this subgroup"
1110	"Physicists and astronomers"
1111	"Mathematicians, statisticians, and adjusters"
1119	"Other professionals who perform an occupation related to this subgroup"
1120	"Chemists"
1121	"Pharmacists"
1129	"Other professionals who perform an occupation related to this subgroup"
1130	"General doctors and specialists"
1131	"Nursing professionals"
1132	"Dentists"
1133	"Optometry professionals"
1134	"Nutrition professionals"
1139	"Other professionals who perform an occupation related to this subgroup"
1140	"Biologists"
1141	"Ecologists and professionals in atmospheric sciences"
1142	"Professionals in ocean sciences and oceanographers"
1149	"Other professionals who perform an occupation related to this subgroup"
1150	"Agronomists"
1151	"Veterinarians and zoo technicians"
1152	"Forestry professionals"
1153	"Fishing and aquaculture professionals"
1159	"Other professionals who perform an occupation related to this subgroup"
1160	"Lawyers"
1161	"Sociologists and demographers"
1162	"Professionals in political sciences and public administration"
1163	"Anthropologists, archeologists, and historians"
1164	"Psychologists"
1165	"Professionals in philosophy and letters"
1166	"Educators"
1167	"Professionals in communication sciences"
1168	"Geographers"
1169	"Other professionals who perform an occupation related to this subgroup"
1170	"Economists"
1171	"Business administrators"
1172	"Public accountants"
1173	"Marketing professionals"
1174	"Professionals in archives, library sciences, and museum studies"
1175	"Professionals in hotel management and tourism"
1179	"Other professionals who perform an occupation related to this subgroup"
1180	"Religious professionals"
1190	"Other professionals who perform an occupation related to this subgroup"
1200	"Drawing technicians"
1201	"Technicians in civil engineering and construction"
1202	"Technicians in mining, metallurgic, and petroleum engineering"
1203	"Technicians in topographic, hydrologic, geologic, and geodesic engineering"
1204	"Technicians in chemical, industrial, and mechanical engineering"
1205	"Technicians in electrical and electronic engineering, informatics, and telecommunications"
1206	"Technicians in the operations of television, filming, projection, image and sound recording equipment, and photographers"
1209	"Other workers who perform an occupation related to this subgroup"
1210	"Physics technicians"
1211	"Technicians in mathematics, statistics, and adjusting"
1219	"Other workers who perform an occupation related to this subgroup"
1220	"Nurses and technicians in human medicine"
1221	"Technicians in dentistry and dental mechanics"
1222	"Technicians in optometry and similar"
1223	"Technicians in nutrition and dieticians"
1229	"Other workers who perform an occupation related to this subgroup"
1230	"Chemical and biological laboratory technicians"
1231	"Pharmaceutical technicians"
1232	"Ecology technicians"
1239	"Other workers who perform an occupation related to this subgroup"
1240	"Agronomy technicians"
1241	"Veterinary technicians and zoo technicians"
1242	"Fishing technicians"
1243	"Technicians in forestry and forestation"
1249	"Other workers who perform an occupation related to this subgroup"
1250	"Technicians in social sciences"
1251	"Technicians in accounting and finance sciences"
1252	"Technicians in administrative, hotel, and tourism sciences"
1260	"Technicians in religious activities"
1290	"Other workers who perform an occupation related to this subgroup"
1300	"University professors and professors in other higher education establishments"
1310	"Professors at preparatory schools and similar"
1320	"Secondary school professors"
1330	"Elementary school professors"
1331	"Literacy teachers"
1332	"Bilingual professors and educators"
1340	"Preschool professors"
1350	"Professors of the mentally handicapped"
1351	"Professors of the visually impaired and blind"
1352	"Professors of persons with hearing and language problems"
1353	"Professors of persons who are physically impaired"
1354	"Professors of persons with learning disabilities"
1359	"Other workers who perform an occupation related to this subgroup"
1360	"Professors and instructors of artistic education"
1361	"Professors and instructors of commercial and administrative studies"
1362	"Professors and instructors of foreign languages"
1363	"Professors, instructors, and trainers in technical education and training applicable in production and services"
1364	"Professors and instructors in sports activities"
1369	"Other workers who perform an occupation related to this subgroup"
1390	"Other workers who perform an occupation related to this subgroup"
1400	"Writers and critics"
1401	"Newspaper reporters and writers"
1410	"Composers and musical arrangers"
1411	"Singers"
1412	"Musicians"
1413	"Actors"
1414	"Dancers"
1419	"Other workers who perform an occupation related to this subgroup"
1420	"Artistic painters and drawers"
1421	"Sculptors and engravers"
1422	"Choreographers and scene directors"
1423	"Decorators and designers"
1429	"Other workers who perform an occupation related to this subgroup"
1430	"Directors of artistic productions"
1431	"Producers and organizers of artistic, cultural, and sports activities"
1432	"Newscasters, conductors, and editorialists in radio and television"
1439	"Other workers who perform an occupation related to this subgroup"
1440	"Sportspersons"
1450	"Umpires and sports judges"
1451	"Sports trainers"
1460	"Animators and announcers"
1461	"Magicians, clowns, contortionists, circus workers and similar occupations in an establishment"
1490	"Other workers who perform an occupation related to this subgroup"
2100	"Higher authorities in government and legislature"
2101	"Municipal presidents and authorities"
2110	"Presidents, directors, and general managers in public, decentralized, and parastate institutions and businesses"
2111	"Presidents, directors, and general managers in private institutions, companies, and businesses"
2119	"Other workers who perform an occupation related to this subgroup"
2120	"Directors, managers, and administrators in the health area or health service businesses"
2121	"Directors, managers, and administrators in the area or business of finance, accounting, human resources, judicial administration"
2122	"Directors, managers, and administrators in the area or business of commercial enterprise (include the sale of insurance and real estate)"
2123	"Directors, managers, and administrators in the area or business of communications and transportation"
2124	"Directors, managers, and administrators in the area or business of industrial manufacturing production, construction, and the services of repair and maintenance"
2125	"Directors, managers, and administrators in the area or business of education and research"
2126	"Directors, managers, and administrators in area or business of assistance services and social readapting"
2127	"Directors, managers, and administrators in the area or business of recreational cultural services, recreation, restaurant, hotels, and other personal services"
2128	"Directors, managers, and administrators in the area or business in the agricultural, forestry, and fishing sectors"
2129	"Other workers who perform an occupation related to this subgroup"
2130	"Directors of political parties"
2131	"Directors of business organizations"
2132	"Directors of labor unions"
2133	"Directors of humanitarian organizations, religious organizations, and civil associations"
2139	"Other workers who perform an occupation related to this subgroup"
2190	"Other workers who perform an occupation related to this group"
4100	"Workers in corn and/or bean crop growing"
4101	"Workers in cereal crop growing"
4102	"Workers in cotton and/or henequen crop growing"
4103	"Workers in horticulture crop growing"
4104	"Workers in coffee and/or cacao crop growing"
4105	"Workers in tobacco crop growing"
4106	"Workers in fruit crop growing"
4107	"Workers in flower crop growing"
4108	"Workers in other agricultural crop growing not mentioned above"
4109	"Other workers who perform an occupation related to this subgroup"
4110	"Workers in bovine cattle breeding"
4111	"Workers in pig breeding"
4112	"Workers in poultry breeding"
4113	"Workers in goat and sheep breeding"
4114	"Workers in beekeeping"
4115	"Workers in equine breeding (horses, donkeys, mules)"
4116	"Workers in breeding animals for decoration, entertainment and laboratories"
4119	"Other workers who perform an occupation related to this subgroup"
4120	"Workers who combine agricultural and cattle raising activities"
4130	"Lumberjacks, loggers, tree cutters, and similar"
4131	"Rubber, gum, resin, and similar harvesters"
4132	"Greenhouse workers"
4133	"Workers in activities of planting, reforestation, and conservation of forests"
4134	"Firewood cutters and collectors"
4135	"Producers of vegetable charcoal"
4136	"Workers in collection of plants, herbs, and roots not cultivated"
4139	"Other workers who perform an occupation related to this subgroup"
4140	"Workers in activities of hunting, trap setting, and similar"
4150	"Fishermen"
4151	"Workers in aquaculture activities"
4159	"Other workers who perform an occupation related to this subgroup"
4160	"Workers in processing activities of agricultural products"
4161	"Workers in processing fishing products"
4169	"Other workers who perform an occupation related to this subgroup"
4170	"Overseers, farm managers, group supervisors and similar in agricultural activities"
4190	"Other workers who perform an occupation related to this subgroup"
5100	"Bosses, coordinators, and similar in the manufacture of foods, beverages, and tobacco products"
5101	"Supervisors, inspectors, and similar in the manufacture of foods, beverages, and tobacco products"
5109	"Other workers who perform an occupation related to this subgroup"
5110	"Bosses, coordinators, and similar in mine, quarry, and well extraction"
5111	"Supervisors, inspectors, and similar in mine, quarry, and well extraction"
5119	"Other workers who perform an occupation related to this subgroup"
5120	"Bosses, coordinators, and similar in the manufacture of textiles, and leather, fur, and similar products"
5121	"Supervisors, inspectors, and similar in the manufacture of textiles, and leather, fur, and similar products"
5129	"Other workers who perform an occupation related to this subgroup"
5130	"Bosses, coordinators, and similar in the manufacture of wood and paper products and printing jobs"
5131	"Supervisors, inspectors, and similar in the manufacture of wood and paper products and printing jobs"
5139	"Other workers who perform an occupation related to this subgroup"
5140	"Bosses, coordinators, and similar in metallurgic manufacturing and the manufacture, repair, and maintenance of machinery and metal products and precision machinery"
5141	"Supervisors, inspectors, and similar in metallurgic manufacturing and the manufacture, repair, and maintenance of machinery and metal products and precision machinery"
5149	"Other workers who perform an occupation related to this subgroup"
5150	"Bosses, coordinators, and similar in the manufacture of products made of ceramic, glass and other non-metal minerals"
5151	"Supervisors, inspectors, and similar in the manufacture of products made of ceramic, glass and other non-metal minerals"
5159	"Other workers who perform an occupation related to this subgroup"
5160	"Bosses, coordinators, contractors, and similar in construction, installation, maintenance, and finishing"
5161	"Supervisors, inspectors, and similar in construction, installation, maintenance, and finishing"
5169	"Other workers who perform an occupation related to this subgroup"
5170	"Bosses, coordinators, and similar in energy generation, installation, repair, and maintenance of electrical equipment and telecommunications"
5171	"Supervisors, inspectors, and similar in energy generation, installation, repair, and maintenance of electrical equipment and telecommunications"
5179	"Other workers who perform an occupation related to this subgroup"
5180	"Bosses, coordinators, and similar in the manufacture of chemicals, petrochemicals, rubber, natural rubber, and plastic"
5181	"Supervisors, inspectors, and similar in the manufacture of chemicals, petrochemicals, rubber, natural rubber, and plastic"
5189	"Other workers who perform an occupation related to this subgroup"
5190	"Other workers who perform an occupation related to this subgroup"
5200	"Workers in the manufacture of meat and fish products and derivatives"
5201	"Workers in the manufacture of dairy products"
5202	"Workers in the manufacture of bread, tortillas, pastries, and other cereal and flour products"
5203	"Workers in the manufacture of products made of fruits and vegetables"
5204	"Workers in the manufacture of sugar-based products, chocolate products, and candy"
5205	"Workers in the manufacture of tobacco products"
5206	"Workers in the manufacture of alcoholic and non-alcoholic beverages"
5207	"Workers in the manufacture of oils, fats, salt, and spices"
5208	"Workers in food preparation"
5209	"Other workers who perform an occupation related to this subgroup"
5210	"Miners"
5211	"Workers in the extraction of quarries, clay, sand, stone, and gravel"
5220	"Fiber preparers and bobbin winders"
5221	"Fiber weavers"
5222	"Tailors, dressmakers, seamstresses who produce complete pieces of clothing made of fabric, leather, fur, and similar"
5223	"Artisans and manufacturers of products made of cloth, leather, fur, and similar (except clothing)"
5224	"Hand embroiderers and hand pulled-thread embroiderers"
5225	"Upholsterers"
5226	"Skinners, cutters, tanners, and painters of leather, skin, and similar"
5227	"Shoemakers and similar workers"
5228	"Pattern makers for cloth, leather, fur, and similar products"
5229	"Other workers who perform an occupation related to this subgroup"
5230	"Carpenters, cabinetmakers, varnishers, wood finishers, and similar in the manufacture of wood products"
5231	"Artisans and factory workers in the manufacture of products made of reeds, sticks, palm, vines, and wicker, except wood"
5232	"Artisans and factory workers in the manufacture of paper and cardboard products"
5233	"Printers, linotypes, photo recorders and similar"
5234	"Photograph and similar developers and printers"
5239	"Other workers who perform an occupation related to this subgroup"
5240	"Mold makers, boilermakers, and lathe workers"
5241	"Welders and oxyfuel cutters"
5242	"Tinsmiths, metal chrome appliers and painters"
5243	"Jewelers, goldsmiths, silversmiths, brass smiths, and copper smiths"
5244	"Locksmiths, metal polishers, and tool sharpeners"
5245	"Mechanics, adjusters, and workers in maintenance and repair of motor vehicles (airplanes, automobiles, etc.)"
5246	"Mechanics, adjusters, installers, and maintenance workers for machinery, industrial instruments, and refrigeration equipment"
5247	"Mechanics, adjusters, installers, and workers for the maintenance and repair of musical instruments (pianos, etc.) and precision instruments (watches, scales, etc.)"
5248	"Blacksmiths, window bar makers, aluminum workers, and forge workers"
5249	"Other workers who perform an occupation related to this subgroup"
5250	"Clay workers and ceramics workers"
5251	"Workers in the manufacture of cement, limestone, chalk, tile, stone, and brick products"
5252	"Workers in glass and similar"
5253	"Workers in the manufacture of products made of bone, shell, coral, and similar"
5259	"Other workers who perform an occupation related to this subgroup"
5260	"Construction day laborers"
5261	"Wide-brush painters"
5262	"Drywall installers and tapers, plasterers and other workers who cover ceilings and walls"
5263	"Roofers (installers of beach umbrellas)"
5264	"Installers of mosaics, tiles, floors, and flagstones"
5265	"Installers of insulation and controlled climates"
5266	"Installers of waterproofing materials, glass, wallpaper, carpets, and other construction materials"
5267	"Plumbers, pipe fitters, and pipe installers"
5269	"Other workers who perform an occupation related to this subgroup"
5270	"Electricians and linemen"
5271	"Installers and repairmen of electronic equipment, electro domestic equipment, and telecommunication equipment"
5272	"Repairmen of electromechanical equipment"
5279	"Other workers who perform an occupation related to this subgroup"
5280	"Workers in the manufacture and repair of rubber, natural rubber, and rubber products and retreading tires"
5281	"Workers in the manufacture of chemical substances and compounds"
5290	"Other workers who perform an occupation related to this subgroup"
5300	"Operators of machinery in the manufacture of meat, fish, and derivatives"
5301	"Operators of machinery in the manufacture of milk and dairy products"
5302	"Operators of machinery in the manufacture of bread, tortillas, pastries, and other cereal- and flour-based products"
5303	"Operators of machinery in the processing of fruits and vegetables"
5304	"Operators of machinery in the manufacture of sugar, coffee, chocolate, tea, and candy"
5305	"Operators of machinery in the manufacture of tobacco products"
5306	"Operators of machinery in the manufacture of alcoholic and non-alcoholic beverages"
5307	"Operators of machinery in the manufacture of oils, fats, salt, and spices"
5309	"Other workers who perform an occupation related to this subgroup"
5310	"Operators of machinery and equipment for extraction in mines and quarries"
5311	"Operators of machinery and equipment for extraction in oil wells"
5312	"Operators of machinery and equipment for obtaining water"
5319	"Other workers who perform an occupation related to this subgroup"
5320	"Operators of machinery for threading and bobbin winding"
5321	"Operators of looms and machinery for manufacturing knit fabrics, other fabrics, and carpets"
5322	"Operators of sewing machines, embroidery machines, and cutting machines for the manufacture of textile products and clothing"
5323	"Operators of machinery for shoemaking and manufacture of leather, fur, and similar goods (except clothing)"
5324	"Operators of machinery for whiting, dying, cleaning, and pressing textile, leather, fur, and similar products"
5329	"Other workers who perform an occupation related to this subgroup"
5330	"Operators of machinery for the treatment of wood, and the manufacture of plywood and pressed woods"
5331	"Operators of machinery for the processing of cellulose and the manufacture of paper and similar products"
5332	"Operators of machinery for the manufacture of wood products and similar (reeds, sticks, palms, wicker, etc.)"
5333	"Operators of machinery for printing and binding"
5334	"Operators of machinery for the manufacture of paper and cardboard products"
5335	"Operators of machinery for developing and printing photographic and similar workers"
5339	"Other workers who perform an occupation related to this subgroup"
5340	"Operators of metallurgic ovens, filters, and laminators"
5341	"Operators of machinery for flattening and thinning metals"
5342	"Operators of machinery for polishing, galvanizing, and coating metals"
5343	"Operators of machinery that cuts, perforates, folds, or otherwise shapes metal parts and products"
5344	"Assemblers and installers of metal tools, machinery, equipment and products"
5345	"Assemblers and installers of electrical and electronic parts"
5349	"Other workers who perform an occupation related to this subgroup"
5350	"Operators of machinery in the manufacture of ceramic products"
5351	"Operators of machinery in the manufacture of mosaic, tile, and similar products"
5352	"Operators of machinery in the manufacture of cement, limestone, chalk, and cement products"
5353	"Operators of machinery in the manufacture of glass and glass products and similar"
5359	"Other workers who perform an occupation related to this subgroup"
5360	"Operators of specialized portable construction equipment (perforator, drill, compressor, etc.)"
5370	"Operators of machinery and installations for electricity generation and distribution"
5371	"Operators of equipment for pumping, ventilation, and refrigeration"
5379	"Other workers who perform an occupation related to this subgroup"
5380	"Operators of machinery for the treatment of chemical substances and water"
5381	"Operators of machinery and equipment for petroleum and natural gas refining"
5382	"Operators of machinery for the manufacture of pharmaceutical and cosmetic products"
5383	"Operators of machinery for the manufacture and assembly of plastic products"
5389	"Other workers who perform an occupation related to this subgroup"
5390	"Other workers who perform an occupation related to this subgroup"
5400	"Assistants, day laborers, and similar in the manufacture of foods, beverages, and tobacco products"
5401	"Loaders, suppliers, manual packers, and similar in the manufacture of foods, beverages, and tobacco products"
5410	"Assistants, day laborers, and similar in mine, quarry, and well extraction"
5411	"Loaders, suppliers, manual packers, and similar in mine, quarry, and well extraction"
5420	"Assistants, day laborers, and similar in the manufacture of textile, leather, fur, and similar products"
5421	"Loaders, suppliers, manual packers, and similar in the manufacture of textile, leather, fur, and similar products"
5430	"Assistants, day laborers, and similar in the manufacture of wood and paper products and printing jobs"
5431	"Loaders, suppliers, manual packers, and similar in the manufacture of wood and paper products and printing jobs"
5440	"Assistants, day laborers, and similar in metallurgic manufacturing and the manufacture of machinery and metal products"
5441	"Loaders, suppliers, manual packers, and similar in metallurgic manufacturing and the manufacture of machinery and metal products"
5450	"Assistants, day laborers, and similar in the manufacture of products made of ceramic, glass and other non-metal minerals"
5451	"Loaders, suppliers, manual packers, and similar in the manufacture of products made of ceramic, glass and other non-metal minerals"
5460	"Assistants, day laborers, and similar in construction"
5461	"Loaders, suppliers, manual packers, and similar in construction"
5470	"Assistants, day laborers, and similar in energy generation, electronics, and telecommunications"
5480	"Assistants, day laborers, and similar in the manufacture of chemicals, petrochemicals, rubber, natural rubber, and plastic"
5481	"Loaders, suppliers, manual packers, and similar in the manufacture of chemicals, petrochemicals, rubber, natural rubber, and plastic"
5490	"Other assistants, day laborers, and similar not classified above"
5491	"Other loaders, suppliers, manual packers, and similar not classified above"
5500	"Conductors of mobile machinery for agriculture and forestry"
5501	"Conductors of mobile machinery for construction"
5502	"Conductors of mobile machinery for merchandize movement"
5509	"Other workers who perform an occupation related to this subgroup"
5510	"Railroad transportation conductors (train, metro, and light train)"
5511	"Railroad transportation conductor's assistants"
5520	"Conductors of buses, trucks, small buses, and automobiles"
5521	"Conductors of trucks, small trucks, and automobiles that transport goods"
5522	"Driver assistants"
5529	"Other workers who perform an occupation related to this subgroup"
5530	"Air transportation pilots"
5540	"Maritime transportation pilots"
5541	"Machinist officials in maritime transportation"
5542	"Deck officers"
5543	"Motor boat, boat, and ship operators"
5549	"Other workers who perform an occupation related to this subgroup"
5550	"Conductors of vehicles pulled by humans"
5551	"Conductors of vehicles pulled by animals (carts, herders)"
5590	"Other workers who perform an occupation related to this subgroup"
6100	"Department heads, coordinators, and supervisors in health services and social assistance"
6101	"Department heads, coordinators, and supervisors in education services"
6102	"Department heads, coordinators, and supervisors in justice administration services and election processes"
6109	"Other workers who perform an occupation related to this subgroup"
6110	"Department heads, coordinators, and supervisors in accounting and finance"
6111	"Department heads, coordinators, and supervisors in administration, human resources, archives and similar"
6120	"Department heads, coordinators, and supervisors in communications"
6121	"Department heads, coordinators, and supervisors in coordination of transportation"
6130	"Department heads, coordinators, and supervisors in statistical and information services"
6131	"Department heads, coordinators, and supervisors in engineering services and similar"
6132	"Department heads, coordinators, and supervisors in social research (history, sociology, psychology, social work, etc.)"
6133	"Department heads, coordinators, and supervisors in other specialized services"
6139	"Other workers who perform an occupation related to this subgroup"
6140	"Department heads, coordinators, and supervisors in infrastructure services (water, electricity, roads, etc.)"
6150	"Department heads, coordinators, and supervisors in cultural and recreational services"
6160	"Department heads, coordinators, and supervisors in restaurant, hotel, and commercial services"
6170	"Department heads, coordinators, and supervisors in agricultural, forestry, and fishing services"
6180	"Other department heads, coordinators, and supervisors in activities not classified above"
6190	"Other workers who perform an occupation related to this subgroup"
6200	"Secretaries"
6201	"Typists, short-hand takers, stenographers, and copiers"
6202	"Data entry"
6203	"Operators of office machinery (copiers, mimeographs, telex, etc.)"
6209	"Other workers who perform an occupation related to this subgroup"
6210	"Cashiers, accounts payable clerks, account collectors"
6211	"Ticket vendors and ticket window employees"
6219	"Other workers who perform an occupation related to this subgroup"
6220	"Workers in archives and correspondence"
6221	"Workers in control of storage and warehouses"
6229	"Other workers who perform an occupation related to this subgroup"
6230	"Receptionists and other workers who provide information"
6231	"Workers in travel agencies"
6232	"Poll-takers, codifiers, verifiers, and similar"
6239	"Other workers who perform an occupation related to this subgroup"
6240	"Telephone operators"
6241	"Telegraph operators"
6249	"Other workers who perform an occupation related to this subgroup"
6250	"Mailmen"
6251	"Workers in general message services"
6259	"Other workers who perform an occupation related to this subgroup"
6260	"Dispatchers, checkers, and similar in transportation operations"
6270	"Other workers in administrative services not classified above"
6290	"Other workers who perform an occupation related to this subgroup"
7100	"Salesmen in establishments"
7110	"Supervisors and caretakers of commercial businesses"
7111	"Dispatchers and employees of commercial businesses"
7120	"Counter workers in stores"
7121	"Deliverymen"
7130	"Sales agents, representatives, distributors and suppliers"
7131	"Real estate agents and workers in real estate rental services (houses, buildings, offices, etc.)"
7132	"Agents of stocks, bonds, and investments"
7133	"Insurance agents"
7134	"Estimators"
7135	"Auctioneers and public auctioneers"
7139	"Other workers who perform an occupation related to this subgroup"
7190	"Other workers who perform an occupation related to this subgroup"
7200	"Traveling salesmen of newspapers and lottery tickets"
7201	"Traveling salesmen of diverse articles"
7209	"Other workers who perform an occupation related to this subgroup"
7210	"People who prepare and sell food on the public roads"
7211	"Shoe shines"
7212	"People who wash cars and take care of cars without an establishment (one the roadside)"
7213	"Clowns, magicians, and similar who perform on the roadside"
7219	"Other workers who perform an occupation related to this subgroup"
7290	"Other workers who perform an occupation related to this subgroup"
8100	"Restaurateurs (prepare and serve food) in establishments"
8101	"Bartenders, waiters, room service attendants"
8102	"Stewardesses and flight attendants"
8109	"Other workers who perform an occupation related to this subgroup"
8110	"Launderers"
8111	"Dyers and pressers"
8120	"Doormen and concierges in establishments"
8121	"Elevator operators"
8122	"Luggage carriers, luggage porters and employees of package and coat checking"
8123	"Hotel servants, bellhops, and similar"
8124	"Workers in cleaning offices, schools, hospitals and other establishments"
8125	"Gardeners"
8126	"Merchandise loaders and unloaders"
8129	"Other workers who perform an occupation related to this subgroup"
8130	"Hairdressers, barbers, stylists, and combers"
8131	"Make-up artists, manicurists, and pedicurists"
8132	"Bath workers and massage therapists"
8139	"Other workers who perform an occupation related to this subgroup"
8140	"Workers in rental services for moveable goods (automobiles, dishes, machinery, etc.)"
8150	"Support workers for entertainment, tourism, and sports activities"
8151	"Workers in personal care and assistance (do not include nurses)"
8152	"Prostitution workers"
8159	"Other workers who perform an occupation related to this subgroup"
8160	"Workers in funeral services and cemeteries"
8190	"Other workers who perform an occupation related to this subgroup"
8200	"Workers in domestic services"
8201	"Persons dedicated to carrying for the elderly, sick, and children in private homes, except nurses"
8202	"Drivers in private households"
8203	"Gardeners in private households"
8204	"Watchmen and doormen in private households"
8209	"Other workers who perform an occupation related to this subgroup"
8290	"Other workers who perform an occupation related to this subgroup"
8300	"Firemen (fire fighters)"
8301	"Policemen and transit agents"
8302	"Detectives"
8303	"Watchmen and guards"
8304	"Personnel in customs and immigration"
8309	"Other workers who perform an occupation related to this subgroup"
8310	"Workers in air forces"
8311	"Workers in the maritime armed forces (navy)"
8312	"Workers in the land armed forces (army)"
8319	"Other workers who perform an occupation related to this subgroup"
8390	"Other workers who perform an occupation related to this subgroup"
9996	"Non-identifiable occupations"
9999	"Unknown"  ;

#delimit cr 

**This do file was created as part of the Economic and Social Research Council funded project:
**Social Networks and Occupational Structure (ESRC grant no: RES-062-23-2497)
**Paul Lambert and Dave Griffiths, University of Stirling
*For more information on the project, see http://www.camsis.stir.ac.uk/sonocs/

 
