**** Value labels for IPUMS, Mexico, 2010

**** Copied from : https://international.ipums.org/international-action/variables/MX10A453#codes_section

** Paul Lambert/Dave Griffiths, Univ. Stirling, 29 November 2012


************************************************


#delimit ; 

capture label drop occlab; 

label define occlab 
 1111 "Top government and judiciary officials"
 1112 "Legislators"
 1113 "Presidents and municipal authorities"
 1121 "Presidents and directors in public institutions"
 1122 "Presidents and directors in private companies and institutions"
 1129 "Other presidents and directors not elsewhere classified"
 1131 "Executives of political organizations"
 1132 "Executives of union organizations"
 1133 "Executives of business organizations"
 1134 "Executives of agricultural organizations"
 1135 "Executives of civil and religious organizations"
 1211 "Directors and managers in human resources management and marketing"
 1212 "Directors and managers in accounting, financial, banking and insurance services"
 1221 "Directors and managers in health services, civil protection and environment"
 1222 "Directors and managers in social and economic development"
 1223 "Directors and managers in schools and training centers"
 1224 "Court judges, directors and managers in legal services and law enforcement"
 1225 "Commanders of the armed forces"
 1226 "Directors in monitoring and security services"
 1311 "Directors and managers in agricultural production, forestry and fishing"
 1312 "Directors and managers in mining, oil and gas production"
 1313 "Directors and managers in the generation and supply of electricity and water"
 1314 "Directors and managers in manufacturing"
 1315 "Directors and managers in construction, repair and maintenance services"
 1321 "Directors and managers in computer sciences"
 1322 "Directors and managers in communications and telecommunication"
 1323 "Directors and managers in transport services"
 1324 "Directors and managers in research and technological development centers"
 1411 "Directors and managers of sales, merchandising, and rental services"
 1412 "Directors and managers of restaurants and hotels"
 1421 "Artistic directors and producers of film, theater and related"
 1422 "Directors and managers of museums, cinemas and other cultural and sporting facilities"
 1423 "Directors and managers in funeral services and other services"
 1511 "Coordinators and department heads in administration, human resources and marketing"
 1512 "Coordinators and department heads in accounting, financial, banking and insurance services"
 1521 "Coordinators and department heads in health services, civil protection and environment"
 1522 "Coordinators and department heads in social and economic development"
 1523 "Coordinators and department heads in schools and training centers"
 1524 "Coordinators and department heads on legal services, judges, and prosecutors"
 1525 "Captains, lieutenants and commanders of the armed forces"
 1526 "Coordinators and leaders in security and surveillance services"
 1611 "Coordinators and department heads in agricultural production, forestry and fishing"
 1612 "Coordinators and department heads in mining, oil and gas production"
 1613 "Coordinators and department heads in the generation and supply of electricity and water"
 1614 "Coordinators and department heads in manufacturing"
 1615 "Coordinators and department heads in construction, repair and maintenance services"
 1619 "Other coordinators and department heads in agricultural production, industrial, construction and maintenance services not elsewhere classified"
 1621 "Coordinators and department heads in computer sciences"
 1622 "Coordinators and department heads in communications and telecommunications"
 1623 "Coordinators and department heads in transport services"
 1624 "Coordinators and department heads in research and technological development centers"
 1629 "Other coordinators and department heads of computers sciences, telecommunications, transport and research and technological development not elsewhere classified"
 1711 "Coordinators and department heads in sales, merchandising, and rental services"
 1712 "Coordinators and heads of area restaurants and hotels"
 1721 "Coordinators and department heads in art, film, theater and related"
 1722 "Coordinators and department heads in museums, cinemas, sports and cultural"
 1723 "Coordinators and department heads at funerals and other services"
 1999 "Other directors, officers, managers, coordinators and department heads not elsewhere classified"
 2111 "Administrators and specialists in human resources and management systems"
 2112 "Specialists and consultants in marketing, advertising, communications and trade"
 2113 "Specialists in hotels and tourism"
 2121 "Accountants and auditors"
 2122 "Financial advisors and analysts"
 2123 "Economists, consultants and researchers in economic policy"
 2131 "Anthropologists, archaeologists, and historians"
 2132 "Researchers and specialists in sociology and social development"
 2133 "Researchers and specialists in political science and public administration"
 2134 "Geographers"
 2135 "Lawyers"
 2141 "Researchers and specialists in philosophy and letters (linguists)"
 2142 "Psychologists"
 2143 "Social workers"
 2144 "Specialists in archives, library, and museums"
 2145 "Priests, pastors and other theologians"
 2151 "Writers and literary critics"
 2152 "Journalists and editors"
 2153 "Translators and interpreters"
 2161 "Painters"
 2162 "Artistic cartoonists illustrators and engravers"
 2163 "Sculptors"
 2164 "Scenographers"
 2171 "Composers and arrangers"
 2172 "Musicians"
 2173 "Singers"
 2174 "Dancers and choreographers"
 2175 "Actors"
 2211 "Researchers and specialists in physics"
 2212 "Researchers and specialists in mathematics, statistics and actuarial sciences"
 2221 "Biologists and marine scientists and oceanographers"
 2222 "Chemicals"
 2223 "Ecologists and atmospheric scientists"
 2231 "Agronomist"
 2232 "Veterinarians and animal husbandry"
 2233 "Specialists in forestry"
 2234 "Specialists in fisheries and in aquaculture"
 2241 "Electrical engineers"
 2242 "Electromechanical engineers"
 2251 "Chemical engineers"
 2252 "Mechanical engineers"
 2253 "Industrial engineers"
 2254 "Mining engineers, metallurgy, and oil"
 2261 "Civil and construction engineers"
 2262 "Engineers in topography, hydrology, geology and geodesy"
 2263 "Architects, urban and transportation planners"
 2271 "Software developers and software and media analysts"
 2272 "Database administrators and computer networks"
 2281 "Communications and telecommunications engineers"
 2311 "Educational supervisors and inspectors"
 2312 "Educators, counselors, educational and other educational scientists"
 2321 "Professors and higher education instructors"
 2322 "Upper secondary teachers and equivalents"
 2331 "Secondary/middle school teachers"
 2332 "Primary school teachers"
 2333 "Literacy specialists"
 2334 "Bilingual education teachers"
 2335 "Preschool teachers"
 2339 "Other entry-level teachers not elsewhere classified"
 2341 "Teachers of people with hearing and speech problems"
 2342 "Teachers of people with learning disabilities"
 2343 "Other special education teachers"
 2411 "General and family doctors"
 2412 "Medical specialists"
 2413 "Dentists"
 2421 "Biomedical engineers"
 2422 "Optometrists"
 2423 "Nutritionist"
 2424 "Health and safety specialists and public health"
 2425 "Specialists in traditional and alternative medicine"
 2426 "Nurses"
 2427 "Physical therapists, audiologists and, speech therapists"
 2428 "Pharmacologists"
 2511 "Aids in administration, marketing, sales and foreign trade"
 2512 "Auxiliary in accounting, economics, finance and brokers"
 2513 "Customs brokers"
 2514 "Appraisers and auctioneers"
 2521 "Official prosecutors and detectives"
 2522 "Customs and border agents"
 2523 "Tax revenue and license agents"
 2524 "Social safety inspectors, prices and other public inspectors"
 2531 "Auxiliary social scientists and humanists"
 2532 "Aids in legal services"
 2533 "Nuns and preachers"
 2541 "Fashion and apparel designers"
 2542 "Industrial designers"
 2543 "Graphic designers"
 2544 "Interior, gardens and various materials (mugs, keychains, etc.) decorators"
 2551 "Announcers on radio, television and other media"
 2552 "Entertainers and event organizers"
 2553 "Clowns, mimes, and circus artists"
 2561 "Sportsmen"
 2562 "Coaches"
 2563 "Sports referees and judges"
 2611 "Auxiliary in physics, mathematics, statistics, and actuarial sciences"
 2612 "Assistants and technicians in the biological, chemical, and environmental sciences"
 2613 "Assistants and technicians in agronomy"
 2614 "Veterinary, fisheries, and forestry assistants and technicians"
 2621 "Industrial and chemical assistants and technicians"
 2622 "Surveyors, hydrology, and geology assistants and technicians"
 2623 "Mining, metallurgy, and oil assistants and technicians"
 2624 "Construction and architecture assistants and technicians"
 2625 "Technical illustrators"
 2630 "Supervisors of mechanics and technicians in maintenance and repair of mechanical equipment, motor vehicles, industrial instruments, and refrigeration equipment"
 2631 "Technical maintenance and repair of motor vehicles"
 2632 "Mechanical maintenance and repair of motor vehicles"
 2633 "Technical maintenance and repair of machinery and industrial instruments"
 2634 "Mechanical maintenance and repair of machinery and industrial instruments"
 2635 "Technical maintenance and repair of precision and musical instruments"
 2636 "Mechanical maintenance and repair of precision and musical instruments"
 2637 "Technicians in the installation, repair, and maintenance of refrigeration, air conditioning, and climate equipment"
 2638 "Mechanical installation, maintenance and repair of refrigeration, air conditioning and climate equipment"
 2639 "Other occupations of mechanics and technicians in the maintenance and repair of mechanical equipment, motor vehicles and industrial instruments not elsewhere classified"
 2640 "Supervisors of electrical technicians, electronics and telecommunications and electromechanical equipment"
 2641 "Electrical technicians"
 2642 "Electricians and linemen"
 2643 "Technicians in installment and repair electronic, telecommunications and appliance (except computer) equipment"
 2644 "Workers in installation and repair of electronic, telecommunications and appliance (except computer) equipment"
 2645 "Technicians repairing electromechanical equipment"
 2646 "Workers repairing electromechanical equipment"
 2649 "Other electrical technicians in electronics and telecommunications, and electromechanical equipment not elsewhere classified"
 2651 "Technicians in the installation and repair of networks, computers and computer systems"
 2652 "Technical operators of radio equipment"
 2653 "Recording and playback equipment assistants and technicians"
 2654 "Audio engineering, sound and lighting assistants and technicians"
 2655 "Photographers"
 2661 "Air traffic controllers"
 2662 "Traffic controllers from other transport (road, rail and sea)"
 2711 "Assistants and technicians in pedagogy and education"
 2712 "Studies and training instructors in art"
 2713 "Studies and training instructors in business and management"
 2714 "Foreign language instructors"
 2715 "Instructors and trainers in trades and work"
 2716 "Teachers in physical education and sport"
 2811 "Nurses (technical)"
 2812 "Diagnostic equipment technicians, medical treatment, podiatrists and physiotherapists"
 2813 "Medical laboratory technicians"
 2814 "Pharmaceutical assistants and technicians"
 2815 "Medical and dental prosthetic technicians"
 2816 "Diet technicians and nutritionists"
 2821 "Nursing assistants and paramedics"
 2822 "Dental assistants and auxiliaries"
 2823 "Hospital and medical auxiliaries"
 2824 "Midwives"
 2825 "Work safety and hygiene technicians"
 2826 "Healers, herbalists and bone-setters"
 2827 "Fumigation and pest control"
 2991 "Other experts not elsewhere classified"
 2992 "Other technicians not elsewhere classified"
 3101 "Supervisors of secretaries, entry operators, cashiers, and file and transport control workers"
 3111 "Secretaries"
 3112 "Stenographers, typists and the like"
 3113 "Data capture"
 3114 "Office machine operators (copier, etc.)."
 3121 "Cashiers, tellers and recipients of gambling"
 3122 "Collectors, payers and lenders"
 3131 "Workers on files and correspondence"
 3132 "Managers and workers in control of stores and warehouses"
 3141 "Transportation dispatchers"
 3142 "Transport inspectors"
 3201 "Supervisors of workers who provide and manage information"
 3211 "Receptionists and workers who provide information (personally)"
 3212 "Workers who provide information by phone (call center) and announcers"
 3213 "Telephone and telegraph workers"
 3221 "Travel agency workers"
 3222 "Tour guides in museums, casinos, parks, cinemas and other recreational facilities"
 3231 "Pollsters"
 3232 "Information encoders"
 3999 "Other secretaries, entry operators, cashiers and workers who provide information not previously classified"
 4111 "Store merchants"
 4201 "Sales managers and supervisors in establishments"
 4211 "Sales workers, dispatchers and clerks"
 4212 "Users and workers on selection of merchandise and vending machines"
 4213 "Telemarketers"
 4214 "Drivers sellers"
 4221 "Agents and sales representatives and shippers"
 4222 "Insurance agents and financial services (account executives)"
 4223 "Real estate agent"
 4224 "Catalog sellers"
 4231 "Demonstrators and promoters"
 4232 "Hostess"
 4233 "Fashion, art and advertising models"
 4311 "Workers in the rental property (houses, land, etc.)."
 4312 "Workers in the rental goods (pottery, movies, video games, etc.)."
 4999 "Other merchants, employees in sales and sales agents not elsewhere classified establishment"
 5101 "Supervisors in the preparation and serving of food and drink"
 5111 "Cooks"
 5112 "Innkeepers"
 5113 "Home cooks"
 5114 "Fast food and taco preparers (appetizers, pizzas, hot dogs, juice, coffee, etc.)"
 5115 "Bartenders"
 5116 "Waiters"
 5201 "Supervisors and workers in personal and household care"
 5211 "Hairdressers, barbers, and stylists"
 5212 "Makeup artists, manicures and pedicures"
 5213 "Lifeguards and masseurs"
 5221 "Caregivers of children, disabled and elderly in institutions"
 5222 "Caregivers of children, disabled and elderly in private homes"
 5231 "Hostesses and attendants"
 5241 "Gardeners in establishments"
 5242 "Homestead gardeners"
 5251 "Astrologers, fortune tellers and related workers"
 5252 "Workers engaged in prostitution"
 5253 "Funeral services workers"
 5254 "Animal trainers and other occupations related to pet care"
 5301 "Supervisors in protection and surveillance services"
 5311 "Firemen"
 5312 "Traffic agents and policemen"
 5313 "Wardens and guards in establishments"
 5314 "Wardens and doormen in private homes"
 5401 "Supervisors of the armed forces"
 5411 "Workers in the air force"
 5412 "Workers in the navy"
 5413 "Workers in the army"
 5999 "Other occupations in personal and surveillance services not elsewhere classified surveillance"
 6101 "Supervisors, farm managers and foremen"
 6111 "Workers in the cultivation of maize and / or beans"
 6112 "Workers in the cultivation of vegetables"
 6113 "Workers in the cultivation of coffee, cocoa and tobacco"
 6114 "Workers in the cultivation of fruits"
 6115 "Workers in the cultivation of flowers"
 6116 "Workers in other crops"
 6117 "Workers in beneficial activities for agricultural products"
 6119 "Other workers in agricultural activities not elsewhere classified"
 6121 "Workers in cattle breeding"
 6122 "Workers in the breeding of pigs"
 6123 "Workers in poultry breeding"
 6124 "Workers in the breeding of goats and sheep"
 6125 "Workers in the breeding of horses"
 6126 "Workers in beekeeping"
 6127 "Workers in the breeding and care of other animals"
 6128 "Workers benefit activities of livestock products"
 6129 "Other workers in livestock and animal husbandry, not elsewhere classified"
 6131 "Workers who combine farming with livestock"
 6201 "Supervisors, managers and supervisors of workers in fisheries, aquaculture, forestry, hunting and the like"
 6211 "Workers in fisheries"
 6212 "Workers on aquaculture activities"
 6213 "Workers in beneficial activities for fisheries or aquaculture products"
 6221 "Loggers, fellers, tree cutters, and the like"
 6222 "Rubber, gum, and resin specialists, and the like"
 6223 "Nursery and greenhouse workers"
 6224 "Workers planting activities, reforestation and forest conservation"
 6225 "Log splitters"
 6226 "Workers collecting non-cultivated plants, herbs, and roots"
 6227 "Charcoal producers"
 6231 "Hunters, trappers, and related workers"
 6311 "Operators of agricultural and forestry machinery"
 6999 "Other workers in agriculture, livestock, forestry, hunting and fishing not elsewhere classified"
 7101 "Supervisors of workers in mining, construction, and building finishing"
 7111 "Mining and extraction workers in the mining of metal ores"
 7112 "Workers in the extraction of quarry, clay, sand, stone and gravel"
 7113 "Blasters and divers in drilling and construction"
 7121 "Bricklayers, stonemasons, and related"
 7122 "Roofers (palapas setters, etc.)."
 7123 "Wood structures carpenter"
 7131 "Plasterers and other walls and ceilings coaters"
 7132 "Installers of floors, tiles, and mosaics"
 7133 "Installers insulation, waterproofing, glass, and other materials"
 7134 "Plumbers and pipe fitters"
 7135 "Painter"
 7201 "Supervisors of artisans and workers in the treatment and processing of metal products"
 7211 "Moulders, turners and cutting workers"
 7212 "Welders and flame cutters"
 7213 "Tinsmiths, sheet metal workers, braziers, and metal painters"
 7214 "Structural-metal preparers and erectors"
 7221 "Blacksmiths, aluminum setters and forging-press workers"
 7222 "Locksmiths, grinders, and tool polishing workers"
 7223 "Jewelers, goldsmiths, silversmiths and metal polishers"
 7301 "Supervisors of artisans and workers in the manufacture of wood, paper, textiles, fur, and leather"
 7311 "Carpenters, joiners, and polishers in the manufacture of wood"
 7312 "Painters and wood varnishers"
 7313 "Artisans working on stick, palm, bamboo, and wicker, except wood"
 7321 "Artisans and workers in the manufacture of paper and cardboard"
 7322 "Printers, typesetters, etchers and binders"
 7323 "Developers and photo printers"
 7331 "Workers in the preparation of fibers and yarns"
 7332 "Fiber weavers"
 7341 "Tailors and dressmakers, seamstresses, and manufacturers of clothing"
 7342 "Artisans and manufacturers of textile products"
 7343 "Sewers and embroiderers"
 7344 "Textile patterns"
 7351 "Upholsterers"
 7352 "Furriers, cutters, tanners and dyers of leather, fur and related products"
 7353 "Artisan shoemakers"
 7401 "Supervisors of artisans and workers in developing rubber products, plastics, and chemicals"
 7411 "Workers in the development and repair of rubber products, plastic, and tire vulcanization"
 7412 "Workers in the production of chemicals and chemical compounds"
 7501 "Supervisors of workers in the processing and food processing, beverages and tobacco"
 7511 "Workers in the production of meat, fish and related products"
 7512 "Workers at the dairy processing"
 7513 "Workers making bread, tortillas, pastries and other flour and cereal products"
 7514 "Workers in the production of fruit and vegetables"
 7515 "Workers in developing sugar-based products, chocolate, candy, and tobacco"
 7516 "Workers in the manufacture of oils, fats, salt and spices"
 7517 "Workers in the production of alcoholic and non alcoholic beverages"
 7601 "Supervisors of artisans and workers in the manufacture of ceramics, glass, tile and similar"
 7611 "Potters and ceramics workers"
 7612 "Workers in the manufacture of cement, lime, plaster, tile, stone and brick"
 7613 "Glass and similar workers"
 7614 "Workers in the manufacture of bone, shell, coral and similar products"
 7999 "Other craft workers not classified above"
 8101 "Supervisors of industrial machinery operators"
 8111 "Machine and equipment operators in extraction activities, mining and quarrying"
 8112 "Machine and equipment operator for extraction in oil wells"
 8113 "Machine and equipment operator for collecting, pumping and distributing water"
 8114 "Specialized mobile equipment operators for construction"
 8121 "Operators of metallurgical furnaces, sieves, and mills and machine operators of metal drawers and extruders"
 8122 "Polishing machine operators, metal plating and coating"
 8123 "Operators of machines that cut, drill, bend, punch, weld, etc.., metal parts and products"
 8131 "Operators of machines for production of chemicals"
 8132 "Operators of machines for production of pharmaceuticals and cosmetics"
 8133 "Operators of machines for the manufacture and assembly of plastic and rubber products"
 8134 "Operators of machines for water treatment"
 8135 "Operators of machines and equipment for oil and gas refining"
 8141 "Operators of machines for wood processing and production of particleboard and plywood"
 8142 "Operators of machines for the manufacture of wood, rattan, wicker and similar"
 8143 "Machine operators in the development of pulp, paper and similar"
 8144 "Operators of machines for printing and binding"
 8145 "Operators of machines for making paper and cardboard products"
 8151 "Machine and equipment operators for spinning and winding"
 8152 "Machine operators to produce knitted fabrics and carpets"
 8153 "Sewing machine operators, embroidery, and cutting for the manufacture of textiles and clothing"
 8154 "Machine operators in leather processing, leather and footwear manufacturing"
 8155 "Machine operators in finishing, bleaching, dyeing, printing, ironing, washing, textiles, leather products, fur, and similar"
 8161 "Machine operators in food processing, oils, fats, salt and spices"
 8162 "Machine operators in the preparation of tobacco"
 8163 "Machine operators in developing alcoholic and non-alcoholic beverages"
 8171 "Machine operators in the production of cement, lime, plaster, and cement products"
 8172 "Machine operators in the production of ceramic, mosaic, tile and similar"
 8173 "Machine operators in making glass, glass products, and the like"
 8181 "Operators of machines and facilities for power generation"
 8199 "Other operators of industrial plant and machinery not elsewhere classified"
 8201 "Supervisors in assembly processes and assembly of machinery, tools and metal and electronic products"
 8211 "Assemblers and fitters of tools, machinery, equipment, and metal products"
 8212 "Assemblers and fitters of electrical and electronic parts"
 8301 "Supervisors of transport and mobile machinery drivers"
 8311 "Aircraft pilots"
 8321 "Captains and ship pilots"
 8322 "Ships' deck officers and deck crews"
 8323 "Ships' engineers"
 8324 "Drivers of small boats"
 8331 "Rail transport conductor (train, metro and light rail)"
 8341 "Drivers of trucks, cargo vans and cars"
 8342 "Drivers of buses, trucks, vans, taxis and passenger cars"
 8343 "Drivers in private homes"
 8344 "Motorcycle driver"
 8349 "Other drivers of motorized land transport not elsewhere classified"
 8351 "Drivers of mobile machinery for construction and mining"
 8352 "Mobile machine drivers for the movement of goods in factories, ports, shops, etc."
 8999 "Other industrial machine operators, assemblers, and transport drivers not elsewhere classified"
 9111 "Support workers in agriculture"
 9112 "Support workers in livestock"
 9113 "Support workers who perform agricultural and livestock activities"
 9121 "Support workers in forestry activities"
 9122 "Support workers in aquaculture and fishing"
 9123 "Support workers hunting and trapping activities"
 9124 "Collectors of firewood and water carriers"
 9211 "Support workers in mining"
 9212 "Support workers in extraction activities"
 9221 "Support workers in the construction"
 9222 "Support workers in plumbing and piping"
 9231 "Support workers in developing, repairing, and maintaining mechanical equipment, machinery and metal and precision products"
 9232 "Support workers in the electrical, electronics, and communications industries"
 9233 "Support workers in the chemical, petrochemical, and plastics industries"
 9234 "Support workers in the wood, paper, and cardboard industry"
 9235 "Support workers in the textile and shoe industries"
 9236 "Support workers in the food, beverages, and tobacco industries"
 9237 "Support workers in the ceramic, glass, and similar industries"
 9239 "Support workers in industrial activities not elsewhere classified"
 9311 "Driver helpers in motorized land transport"
 9312 "Driver helpers in railways transport"
 9321 "Drivers of cycling transportation vehicles"
 9322 "Drivers of animal-powered transport (carts, carriers)"
 9331 "Loaders"
 9332 "Loaders receiving tips"
 9411 "Helpers in food preparation"
 9511 "Newspaper and lottery vendors"
 9512 "Street vendors of diverse products (excluding food sales)"
 9521 "Preparers and street food vendors"
 9601 "Supervisors in cleaning, housekeeping, of butlers and parking lots"
 9611 "Domestic workers"
 9621 "Sweepers and janitors (except in hotels and restaurants)"
 9622 "Room maids and maids"
 9623 "Hotel and restaurant waiters"
 9624 "Shoe cleaners"
 9631 "Vehicle cleaners in establishments"
 9632 "Vehicle cleaners in the street"
 9633 "Valet parking and vehicle caretakers in parking lots"
 9634 "Vehicle caretakers receiving tips"
 9641 "Launderers in establishments"
 9642 "Pressers and dry cleaners in establishments"
 9643 "Domestic launderers and pressers"
 9651 "Assistant gardener"
 9661 "Garbage and recyclable material collectors"
 9662 "Waste sorter"
 9663 "Collectors of other materials"
 9711 "Parcel workers, hotel porters and buttons"
 9712 "Packers of objects and goods"
 9713 "Support workers in the performance of shows, sports, and in amusement parks"
 9721 "Postmen (walking and cycling)"
 9722 "Mail deliverers (walking and cycling) and messengers"
 9723 "Deliverers of goods (walking and cycling)"
 9731 "Meter readers"
 9732 "Money collectors"
 9733 "Elevator operators"
 9888 "Other workers in elementary and support activities not elsewhere classified"
 9998 "Unknown"
 9999 "NIU (not in universe)" ; 


#delimit cr 




**This do file was created as part of the Economic and Social Research Council funded project:
**Social Networks and Occupational Structure (ESRC grant no: RES-062-23-2497)
**Paul Lambert and Dave Griffiths, University of Stirling
*For more information on the project, see http://www.camsis.stir.ac.uk/sonocs/

 