**** Value labels for IPUMS, Vietnam, 2009

**** Copied from : https://international.ipums.org/international-action/variables/VN09A416#codes_section

** Paul Lambert/Dave Griffiths, Univ. Stirling, 12 November 2012


************************************************


#delimit ; 

capture label drop occlab; 

label define occlab
0 "Armed forces occupations" 
10 "Commissioned armed forces officers" 
20 "Non-commissioned armed forces officers" 
30 "Other armed forces occupations" 
100 "Leaders, managers and administrators of branches, levels and organizations" 
111 "Vietnam communist party leaders at national level" 
112 "Vietnam communist party leaders of province level" 
113 "Vietnam communist party leaders of district level" 
114 "Vietnam communist party leaders of commune level" 
115 "Vietnam communist party leaders at enterprises and organizations" 
121 "Leaders of the national assembly (full time)" 
122 "Leaders of office of the country's president" 
131 "Leaders of government" 
132 "Leaders of government ministries, branches and equivalent" 
133 "Leaders of general offices under ministries" 
140 "Leaders of people's court and procuracy, unspecified" 
141 "Leaders of people's supreme court and procuracy" 
142 "Leaders of people's local court and procuracy" 
143 "Leaders of other courts (excluding army court ) in accordance with the law" 
150 "Leaders of local people's council and people's committee (including local specialized office, excluding justice and union offices), unspecified" 
151 "Leaders of people's council (full time)" 
152 "Leaders of people's committee (including specialized offices)" 
160 "Leaders of unions: fatherland front, labour union, women union, farmer union, communist youth union, war veteran union, unspecified" 
161 "Leaders of unions (excluding labour union) (full time)" 
162 "Leaders of labour union (full time)" 
171 "Leaders of trade union (full time)" 
172 "Leaders of humanity organizations and for other special interests (full time)" 
181 "Chairmen, deputy chairmen of board of directors, directors general, deputy directors general, rectors, deputy rectors of big universities" 
182 "Directors, deputy directors of production and implementation units belong to corporations, head of company, big university and equivalent" 
183 "Directors, deputy directors of management units belong to corporations, head of company, big university and equivalent" 
184 "Directors, deputy directors of company, enterprise, factory; rectors, deputy rectors of small colleges" 
210 "Science and technical professionals, unspecified" 
211 "Physical and earth science professionals" 
212 "Mathematics and statistics professionals" 
213 "Life science and health professionals" 
214 "Technical professionals (excluding electrical technique)" 
215 "Electrical engineers" 
216 "Architects, engineers and related professionals" 
220 "Life science and health professionals, unspecified" 
221 "Health professionals (excluding nursing)" 
222 "Nursing and midwifery professionals" 
223 "Traditional medicine and aid medicine professionals" 
224 "Assistant doctor professionals" 
225 "Veterinary professionals" 
226 "Other health professionals" 
230 "Teaching professionals, unspecified" 
231 "College, university and higher education teaching professionals" 
232 "Trade teaching professionals" 
233 "Secondary education teaching professionals" 
234 "Primary and pre-primary education teaching professionals" 
235 "Other teaching professionals not elsewhere classified (new)" 
240 "Business and management professionals, unspecified" 
241 "Financial professionals" 
242 "Management professionals" 
243 "Sales, marketing and public relations professionals" 
244 "Government adjustment professionals" 
250 "Information technology and telecommunications professionals, unspecified" 
251 "Analysis and development software and applications professionals" 
252 "Database and network professionals" 
260 "Legal, social and cultural professionals, unspecified" 
261 "Legal professionals" 
262 "Archivists, librarians and related information professionals" 
263 "Social and religion professionals" 
264 "Writers, journalists and linguists" 
265 "Creative and performing artists" 
310 "Science and engineering associate professionals, unspecified" 
311 "Physical science and engineering associate professionals" 
312 "Mining, manufacturing and building inspectors" 
313 "Checking, operating and controlling procedure technicians" 
314 "Life sciences and related technicians" 
315 "Ship and aircraft controllers and technicians" 
320 "Health associate professionals, unspecified" 
321 "Health and pharmaceutics associate professionals" 
322 "Nursing and midwifery associate professionals" 
323 "Traditional medicine practitioners and related technicians" 
324 "Veterinary associate professionals and related technicians" 
325 "Other health associate professionals" 
330 "Business and management associate professionals, unspecified" 
331 "Applied mathematics and finance associate professionals" 
332 "Sales and trade agents and brokers" 
333 "Business services employee agents" 
334 "Administrative associate professionals" 
335 "Government adjustment associate professionals" 
340 "Legal, social and cultural associate professionals, unspecified" 
341 "Legal, social and religion associate professionals" 
342 "Sports and sports training associate professionals" 
343 "Fine art, culture and cooking associate professionals" 
350 "Information technology and telecommunications associate professionals, unspecified" 
351 "User and operator assistant associate professionals in information technology and telecommunications" 
352 "Telecom and television technicians" 
360 "Teaching associate professionals, unspecified" 
361 "Primary education teaching associate professionals" 
362 "Pre-primary education teaching associate professionals" 
363 "Special education teaching associate professionals" 
364 "Other teaching associate professionals" 
400 "Clerks, unspecified" 
410 "Office clerks, unspecified" 
411 "General office clerks" 
412 "Secretaries (general)" 
413 "Keyboard operating clerks" 
420 "Customer services clerks, unspecified" 
421 "Cashiers, tellers and related clerks" 
422 "Client information clerks" 
430 "Data and note-taking clerks, unspecified" 
431 "Data clerks and related clerks" 
432 "Note-taking clerks" 
440 "Other office clerks" 
500 "Service workers and market sales workers" 
510 "Personal services workers, unspecified" 
511 "Travel attendants and guides" 
512 "Cooks" 
513 "Waiters and bartenders" 
514 "Hairdressers, barbers, beauticians and related workers" 
515 "House stewards and housekeepers" 
516 "Other personal services workers" 
520 "Salespersons, unspecified" 
521 "Street and market salespersons" 
522 "Shop salespersons" 
523 "Cashier, tellers and related clerks" 
524 "Other salespersons" 
530 "Personal care services workers, unspecified" 
531 "Child care workers and associate teachers" 
532 "Nursing and personal health care workers" 
540 "Protective services workers, unspecified" 
600 "Skilled agricultural, forestry and fishery workers" 
610 "Commercial skilled agricultural workers, unspecified" 
611 "Commercial gardeners and crop growers" 
612 "Commercial animal producers" 
613 "Commercial crop and animal producers" 
620 "Commercial skilled forestry, fishery and hunting workers, unspecified" 
621 "Commercial skilled forestry and related workers" 
622 "Commercial skilled fishery and hunting workers" 
630 "Subsistence agricultural, fishery, hunting and gathering workers, unspecified" 
631 "Subsistence agricultural workers" 
632 "Subsistence animal producers" 
633 "Subsistence crop and animal producers" 
634 "Subsistence fishery, hunting,  trapping and gathering workers" 
710 "Building trades workers and related workers (excluding electricians), unspecified" 
711 "Building frame and related trades workers" 
712 "Building finishers and related trades workers" 
713 "Painters, building structure cleaners and related workers" 
720 "Metal and machinery trades workers, unspecified" 
721 "Metal molders, welders, sheet-metal workers, structural metal prepares, and related workers" 
722 "Blacksmiths, toolmakers and related workers" 
723 "Machinery mechanics and fitters" 
730 "Precision, handicraft, printing and related trades workers, unspecified" 
731 "Handicraft workers" 
732 "Printing and related trades workers" 
740 "Electrical and electronic workers, unspecified" 
741 "Electrical instrument repairers and fitters" 
742 "Telecommunication instrument repairers and fitters" 
750 "Food, wood, textile, garment and related products processing trades workers, unspecified" 
751 "Food and related products processing trades workers" 
752 "Wood, wood products and related processing trades workers" 
753 "Textile, garment and related products processing trades workers" 
754 "Other handicraft and related trades workers" 
800 "Plant, machine operators and assemblers" 
810 "Stationary instrument and machine operators, unspecified" 
811 "Mineral products processing machine operators" 
812 "Metal products processing machine operators" 
813 "Chemical, photographic and film products machine operators" 
814 "Paper,  plastic and rubber products machine operators" 
815 "Textile material, leather, animal feather products machine operators" 
816 "Food and related products processing machine operators" 
817 "Paper and wood products machine operators" 
818 "Other machine and instrument operators" 
820 "Assemblers" 
830 "Drivers and mobile machinery operators, unspecified" 
831 "Railway engine drivers and related workers" 
832 "Passenger car, van and motorcycle drivers" 
833 "Middle lorry, heavy truck and bus drivers" 
834 "Mobile machinery operators" 
835 "Ships? deck crews and related workers" 
900 "Elementary occupations" 
910 "Domestic helpers and cleaners and related workers, unspecified" 
911 "Domestic, hotel, office helpers and cleaners" 
912 "Car, window cleaners, laundry persons and related workers using hands" 
920 "Agricultural, forestry, fishery labourers" 
930 "Labourers in mining, construction, manufacturing and transport, unspecified" 
931 "Labourers in mining and construction" 
932 "Labourers in manufacturing" 
933 "Labourers in transport and warehouse" 
940 "Helpers in food preparing" 
950 "Sales and services elementary occupations, unspecified" 
951 "Labourers in street and related labourers" 
952 "Street vendors, other products (excluding street food vendors)" 
960 "Garbage collectors and other elementary labourers, unspecified" 
961 "Garbage collectors and related labourers" 
962 "Other elementary labourers" 
998 "Unknown" 
999 "NIU (not in the universe)"     ;


#delimit cr 




**This do file was created as part of the Economic and Social Research Council funded project:
**Social Networks and Occupational Structure (ESRC grant no: RES-062-23-2497)
**Paul Lambert and Dave Griffiths, University of Stirling
*For more information on the project, see http://www.camsis.stir.ac.uk/sonocs/


