

***** 

** Defines UK SOC2010 labels in a Stata label item:

* [Copied by Paul Lambert, Univ. Stirling, 2011, for the DAMES project www.dames.org.uk] 

* Original source: http://www.ons.gov.uk/about-statistics/classifications/current/soc2010/soc2010-volume-3-ns-sec--rebased-on-soc2010--user-manual/index.html

****

#delimit; 

capture label drop soc2010l;
 
label define soc2010l  
 1115 "Chief executives and senior officials" 
 1116 "Elected officers and representatives" 
 1121 "Production managers and directors in manufacturing" 
 1122 "Production managers and directors in construction" 
 1123 "Production managers and directors in mining and energy" 
 1131 "Financial managers and directors" 
 1132 "Marketing and sales directors" 
 1133 "Purchasing managers and directors" 
 1134 "Advertising and public relations directors" 
 1135 "Human resource managers and directors" 
 1136 "Information technology and telecommunications directors" 
 1139 "Functional managers and directors n.e.c." 
 1150 "Financial institution managers and directors" 
 1161 "Managers and directors in transport and distribution" 
 1162 "Managers and directors in storage and warehousing" 
 1171 "Officers in armed forces" 
 1172 "Senior police officers" 
 1173 "Senior officers in fire, ambulance, prison and related services" 
 1181 "Health services and public health managers and directors" 
 1184 "Social services managers and directors" 
 1190 "Managers and directors in retail and wholesale" 
 1211 "Managers and proprietors in agriculture and horticulture" 
 1213 "Managers and proprietors in forestry, fishing and related services" 
 1221 "Hotel and accommodation managers and proprietors" 
 1223 "Restaurant and catering establishment managers and proprietors" 
 1224 "Publicans and managers of licensed premises" 
 1225 "Leisure and sports managers" 
 1226 "Travel agency managers and proprietors" 
 1241 "Health care practice managers" 
 1242 "Residential, day and domiciliary care managers and proprietors" 
 1251 "Property, housing and estate managers" 
 1252 "Garage managers and proprietors" 
 1253 "Hairdressing and beauty salon managers and proprietors" 
 1254 "Shopkeepers and proprietors – wholesale and retail" 
 1255 "Waste disposal and environmental services managers" 
 1259 "Managers and proprietors in other services n.e.c." 
 2111 "Chemical scientists" 
 2112 "Biological scientists and biochemists" 
 2113 "Physical scientists" 
 2114 "Social and humanities scientists" 
 2119 "Natural and social science professionals n.e.c." 
 2121 "Civil engineers" 
 2122 "Mechanical engineers" 
 2123 "Electrical engineers" 
 2124 "Electronics engineers" 
 2126 "Design and development engineers" 
 2127 "Production and process engineers" 
 2129 "Engineering professionals n.e.c." 
 2133 "IT specialist managers" 
 2134 "IT project and programme managers" 
 2135 "IT business analysts, architects and systems designers" 
 2136 "Programmers and software development professionals" 
 2137 "Web design and development professionals" 
 2139 "Information technology and telecommunications professionals n.e.c." 
 2141 "Conservation professionals" 
 2142 "Environment professionals" 
 2150 "Research and development managers" 
 2211 "Medical practitioners" 
 2212 "Psychologists" 
 2213 "Pharmacists" 
 2214 "Ophthalmic opticians" 
 2215 "Dental practitioners" 
 2216 "Veterinarians" 
 2217 "Medical radiographers" 
 2218 "Podiatrists" 
 2219 "Health professionals n.e.c." 
 2221 "Physiotherapists" 
 2222 "Occupational therapists" 
 2223 "Speech and language therapists" 
 2229 "Therapy professionals n.e.c." 
 2231 "Nurses" 
 2232 "Midwives" 
 2311 "Higher education teaching professionals" 
 2312 "Further education teaching professionals" 
 2314 "Secondary education teaching professionals" 
 2315 "Primary and nursery education teaching professionals" 
 2316 "Special needs education teaching professionals" 
 2317 "Senior professionals of educational establishments" 
 2318 "Education advisers and school inspectors" 
 2319 "Teaching and other educational professionals n.e.c." 
 2412 "Barristers and judges" 
 2413 "Solicitors" 
 2419 "Legal professionals n.e.c." 
 2421 "Chartered and certified accountants" 
 2423 "Management consultants and business analysts" 
 2424 "Business and financial project management professionals" 
 2425 "Actuaries, economists and statisticians" 
 2426 "Business and related research professionals" 
 2429 "Business, research and administrative professionals n.e.c." 
 2431 "Architects" 
 2432 "Town planning officers" 
 2433 "Quantity surveyors" 
 2434 "Chartered surveyors" 
 2435 "Chartered architectural technologists" 
 2436 "Construction project managers and related professionals" 
 2442 "Social workers" 
 2443 "Probation officers" 
 2444 "Clergy" 
 2449 "Welfare professionals n.e.c." 
 2451 "Librarians" 
 2452 "Archivists and curators" 
 2461 "Quality control and planning engineers" 
 2462 "Quality assurance and regulatory professionals" 
 2463 "Environmental health professionals" 
 2471 "Journalists, newspaper and periodical editors" 
 2472 "Public relations professionals" 
 2473 "Advertising accounts managers and creative directors" 
 3111 "Laboratory technicians" 
 3112 "Electrical and electronics technicians" 
 3113 "Engineering technicians" 
 3114 "Building and civil engineering technicians" 
 3115 "Quality assurance technicians" 
 3116 "Planning, process and production technicians" 
 3119 "Science, engineering and production technicians n.e.c." 
 3121 "Architectural and town planning technicians" 
 3122 "Draughtspersons" 
 3131 "IT operations technicians" 
 3132 "IT user support technicians" 
 3213 "Paramedics" 
 3216 "Dispensing opticians" 
 3217 "Pharmaceutical technicians" 
 3218 "Medical and dental technicians" 
 3219 "Health associate professionals n.e.c." 
 3231 "Youth and community workers" 
 3233 "Child and early years officers" 
 3234 "Housing officers" 
 3235 "Counsellors" 
 3239 "Welfare and housing associate professionals n.e.c." 
 3311 "NCOs and other ranks" 
 3312 "Police officers (sergeant and below)" 
 3313 "Fire service officers (watch manager and below)" 
 3314 "Prison service officers (below principal officer)" 
 3315 "Police community support officers" 
 3319 "Protective service associate professionals n.e.c." 
 3411 "Artists" 
 3412 "Authors, writers and translators" 
 3413 "Actors, entertainers and presenters" 
 3414 "Dancers and choreographers" 
 3415 "Musicians" 
 3416 "Arts officers, producers and directors" 
 3417 "Photographers, audio-visual and broadcasting equipment operators" 
 3421 "Graphic designers" 
 3422 "Product, clothing and related designers" 
 3441 "Sports players" 
 3442 "Sports coaches, instructors and officials" 
 3443 "Fitness instructors" 
 3511 "Air traffic controllers" 
 3512 "Aircraft pilots and flight engineers" 
 3513 "Ship and hovercraft officers" 
 3520 "Legal associate professionals" 
 3531 "Estimators, valuers and assessors" 
 3532 "Brokers" 
 3533 "Insurance underwriters" 
 3534 "Finance and investment analysts and advisers" 
 3535 "Taxation experts" 
 3536 "Importers and exporters" 
 3537 "Financial and accounting technicians" 
 3538 "Financial accounts managers" 
 3539 "Business and related associate professionals n.e.c." 
 3541 "Buyers and procurement officers" 
 3542 "Business sales executives" 
 3543 "Marketing associate professionals" 
 3544 "Estate agents and auctioneers" 
 3545 "Sales accounts and business development managers" 
 3546 "Conference and exhibition managers and organisers" 
 3550 "Conservation and environmental associate professionals" 
 3561 "Public services associate professionals" 
 3562 "Human resources and industrial relations officers" 
 3563 "Vocational and industrial trainers and instructors" 
 3564 "Careers advisers and vocational guidance specialists" 
 3565 "Inspectors of standards and regulations" 
 3567 "Health and safety officers" 
 4112 "National government administrative occupations" 
 4113 "Local government administrative occupations" 
 4114 "Officers of non-governmental organisations" 
 4121 "Credit controllers" 
 4122 "Book-keepers, payroll managers and wages clerks" 
 4123 "Bank and post office clerks" 
 4124 "Finance officers" 
 4129 "Financial administrative occupations n.e.c." 
 4131 "Records clerks and assistants" 
 4132 "Pensions and insurance clerks and assistants" 
 4133 "Stock control clerks and assistants" 
 4134 "Transport and distribution clerks and assistants" 
 4135 "Library clerks and assistants" 
 4138 "Human resources administrative occupations" 
 4151 "Sales administrators" 
 4159 "Other administrative occupations n.e.c." 
 4161 "Office managers" 
 4162 "Office supervisors" 
 4211 "Medical secretaries" 
 4212 "Legal secretaries" 
 4213 "School secretaries" 
 4214 "Company secretaries" 
 4215 "Personal assistants and other secretaries" 
 4216 "Receptionists" 
 4217 "Typists and related keyboard occupations" 
 5111 "Farmers" 
 5112 "Horticultural trades" 
 5113 "Gardeners and landscape gardeners" 
 5114 "Groundsmen and greenkeepers" 
 5119 "Agricultural and fishing trades n.e.c." 
 5211 "Smiths and forge workers" 
 5212 "Moulders, core makers, die casters" 
 5213 "Sheet metal workers" 
 5214 "Metal plate workers, and riveters" 
 5215 "Welding trades" 
 5216 "Pipe fitters" 
 5221 "Metal machining setters and setter-operators" 
 5222 "Tool makers, tool fitters and markers-out" 
 5223 "Metal working production and maintenance fitters" 
 5224 "Precision instrument makers and repairers" 
 5225 "Air-conditioning and refrigeration engineers" 
 5231 "Vehicle technicians, mechanics and electricians" 
 5232 "Vehicle body builders and repairers" 
 5234 "Vehicle paint technicians" 
 5235 "Aircraft maintenance and related trades" 
 5236 "Boat and ship builders and repairers" 
 5237 "Rail and rolling stock builders and repairers" 
 5241 "Electricians and electrical fitters" 
 5242 "Telecommunications engineers" 
 5244 "TV, video and audio engineers" 
 5245 "IT engineers" 
 5249 "Electrical and electronic trades n.e.c." 
 5250 "Skilled metal, electrical and electronic trades supervisors" 
 5311 "Steel erectors" 
 5312 "Bricklayers and masons" 
 5313 "Roofers, roof tilers and slaters" 
 5314 "Plumbers and heating and ventilating engineers" 
 5315 "Carpenters and joiners" 
 5316 "Glaziers, window fabricators and fitters" 
 5319 "Construction and building trades n.e.c." 
 5321 "Plasterers" 
 5322 "Floorers and wall tilers" 
 5323 "Painters and decorators" 
 5330 "Skilled construction and building trades supervisors" 
 5411 "Weavers and knitters" 
 5412 "Upholsterers" 
 5413 "Footwear and leather working trades" 
 5414 "Tailors and dressmakers" 
 5419 "Textiles, garments and related trades n.e.c." 
 5421 "Pre-press technicians" 
 5422 "Printers" 
 5423 "Print finishing and binding workers" 
 5431 "Butchers" 
 5432 "Bakers and flour confectioners" 
 5433 "Fishmongers and poultry dressers" 
 5434 "Chefs" 
 5435 "Cooks" 
 5436 "Catering and bar managers" 
 5441 "Glass and ceramics makers, decorators and finishers" 
 5442 "Furniture makers and other craft woodworkers" 
 5443 "Florists" 
 5449 "Other skilled trades n.e.c." 
 6121 "Nursery nurses and assistants" 
 6122 "Childminders and related occupations" 
 6123 "Playworker" 
 6125 "Teaching assistants" 
 6126 "Educational support assistants" 
 6131 "Veterinary nurses" 
 6132 "Pest control officers" 
 6139 "Animal care services occupations n.e.c." 
 6141 "Nursing auxiliaries and assistants" 
 6142 "Ambulance staff (excluding paramedics)" 
 6143 "Dental nurses" 
 6144 "Houseparents and residential wardens" 
 6145 "Care workers and home carers" 
 6146 "Senior care workers" 
 6147 "Care escorts" 
 6148 "Undertakers, mortuary and crematorium assistants" 
 6211 "Sports and leisure assistants" 
 6212 "Travel agents" 
 6214 "Air travel assistants" 
 6215 "Rail travel assistants" 
 6219 "Leisure and travel service occupations n.e.c." 
 6221 "Hairdressers and barbers" 
 6222 "Beauticians and related occupations" 
 6231 "Housekeepers and related occupations" 
 6232 "Caretakers" 
 6240 "Cleaning and housekeeping managers and supervisors" 
 7111 "Sales and retail assistants" 
 7112 "Retail cashiers and check-out operators" 
 7113 "Telephone salespersons" 
 7114 "Pharmacy and other dispensing assistants" 
 7115 "Vehicle and parts salespersons and advisers" 
 7121 "Collector salespersons and credit agents" 
 7122 "Debt, rent and other cash collectors" 
 7123 "Roundspersons and van salespersons" 
 7124 "Market and street traders and assistants" 
 7125 "Merchandisers and window dressers" 
 7129 "Sales related occupations n.e.c." 
 7130 "Sales supervisors" 
 7211 "Call and contact centre occupations" 
 7213 "Telephonists" 
 7214 "Communication operators" 
 7215 "Market research interviewers" 
 7219 "Customer service occupations n.e.c." 
 7220 "Customer service managers and supervisors" 
 8111 "Food, drink and tobacco process operatives" 
 8112 "Glass and ceramics process operatives" 
 8113 "Textile process operatives" 
 8114 "Chemical and related process operatives" 
 8115 "Rubber process operatives" 
 8116 "Plastics process operatives" 
 8117 "Metal making and treating process operatives" 
 8118 "Electroplaters" 
 8119 "Process operatives n.e.c." 
 8121 "Paper and wood machine operatives" 
 8122 "Coal mine operatives" 
 8123 "Quarry workers and related operatives" 
 8124 "Energy plant operatives" 
 8125 "Metal working machine operatives" 
 8126 "Water and sewerage plant operatives" 
 8127 "Printing machine assistants" 
 8129 "Plant and machine operatives n.e.c." 
 8131 "Assemblers (electrical and electronic products)" 
 8132 "Assemblers (vehicles and metal goods)" 
 8133 "Routine inspectors and testers" 
 8134 "Weighers, graders and sorters" 
 8135 "Tyre, exhaust and windscreen fitters" 
 8137 "Sewing machinists" 
 8139 "Assemblers and routine operatives n.e.c." 
 8141 "Scaffolders, stagers and riggers" 
 8142 "Road construction operatives" 
 8143 "Rail construction and maintenance operatives" 
 8149 "Construction operatives n.e.c." 
 8211 "Large goods vehicle drivers" 
 8212 "Van drivers" 
 8213 "Bus and coach drivers" 
 8214 "Taxi and cab drivers and chauffeurs" 
 8215 "Driving instructors" 
 8221 "Crane drivers" 
 8222 "Fork-lift truck drivers" 
 8223 "Agricultural machinery drivers" 
 8229 "Mobile machine drivers and operatives n.e.c." 
 8231 "Train drivers" 
 8232 "Marine and waterways transport operatives" 
 8233 "Air transport operatives" 
 8234 "Rail transport operatives" 
 8239 "Other drivers and transport operatives n.e.c." 
 9111 "Farm workers" 
 9112 "Forestry workers" 
 9119 "Fishing and other elementary agriculture occupations n.e.c." 
 9120 "Elementary construction occupations" 
 9132 "Industrial cleaning process occupations" 
 9134 "Packers, bottlers, canners and fillers" 
 9139 "Elementary process plant occupations n.e.c." 
 9211 "Postal workers, mail sorters, messengers and couriers" 
 9219 "Elementary administration occupations n.e.c." 
 9231 "Window cleaners" 
 9232 "Street cleaners" 
 9233 "Cleaners and domestics" 
 9234 "Launderers, dry cleaners and pressers" 
 9235 "Refuse and salvage occupations" 
 9236 "Vehicle valeters and cleaners" 
 9239 "Elementary cleaning occupations n.e.c." 
 9241 "Security guards and related occupations" 
 9242 "Parking and civil enforcement occupations" 
 9244 "School mid-day and crossing patrol occupations" 
 9249 "Elementary security occupations n.e.c." 
 9251 "Shelf fillers" 
 9259 "Elementary sales occupations n.e.c." 
 9260 "Elementary storage occupations" 
 9271 "Hospital porters" 
 9272 "Kitchen and catering assistants" 
 9273 "Waiters and waitresses" 
 9274 "Bar staff" 
 9275 "Leisure and theme park attendants" 
 9279 "Other elementary services occupations n.e.c." ; 

#delimit cr


*******

** EOF 

 
